/*
 * Copyright 2016 CIRDLES.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 * Any modifications to this file will be lost upon recompilation of the source schema. 
 * Generated on: 2016.03.03 at 09:06:25 AM EST 
 */
package org.geosamples.samples;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for MacrobiologyDetails.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * {@code
 * <xml>
 * <simpleType name="MacrobiologyDetails">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Coral"/>
 *   </restriction>
 * </simpleType>
 * </xml>
 * }
 * </pre>
 *
 */
@XmlType(name = "MacrobiologyDetails")
@XmlEnum
public enum MacrobiologyDetails {

    @XmlEnumValue("Coral")
    CORAL("Coral");
    private final String value;

    MacrobiologyDetails(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MacrobiologyDetails fromValue(String v) {
        for (MacrobiologyDetails c : MacrobiologyDetails.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
