//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 09:36:17 AM EDT 
//


package org.geosamples.samples;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for material.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="material"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Biology"/&gt;
 *     &lt;enumeration value="Gas"/&gt;
 *     &lt;enumeration value="Ice"/&gt;
 *     &lt;enumeration value="Liquid&gt;aqueous"/&gt;
 *     &lt;enumeration value="Liquid&gt;organic"/&gt;
 *     &lt;enumeration value="Mineral"/&gt;
 *     &lt;enumeration value="Not applicable"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *     &lt;enumeration value="Particulate"/&gt;
 *     &lt;enumeration value="Rock"/&gt;
 *     &lt;enumeration value="Sediment"/&gt;
 *     &lt;enumeration value="Soil"/&gt;
 *     &lt;enumeration value="Synthetic"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "material", namespace = "http://app.geosamples.org")
@XmlEnum
public enum Material {

    @XmlEnumValue("Biology")
    BIOLOGY("Biology"),
    @XmlEnumValue("Gas")
    GAS("Gas"),
    @XmlEnumValue("Ice")
    ICE("Ice"),
    @XmlEnumValue("Liquid>aqueous")
    LIQUID_AQUEOUS("Liquid>aqueous"),
    @XmlEnumValue("Liquid>organic")
    LIQUID_ORGANIC("Liquid>organic"),
    @XmlEnumValue("Mineral")
    MINERAL("Mineral"),
    @XmlEnumValue("Not applicable")
    NOT_APPLICABLE("Not applicable"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Particulate")
    PARTICULATE("Particulate"),
    @XmlEnumValue("Rock")
    ROCK("Rock"),
    @XmlEnumValue("Sediment")
    SEDIMENT("Sediment"),
    @XmlEnumValue("Soil")
    SOIL("Soil"),
    @XmlEnumValue("Synthetic")
    SYNTHETIC("Synthetic");
    private final String value;

    Material(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Material fromValue(String v) {
        for (Material c: Material.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
