//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 10:31:23 AM EDT 
//


package org.geosamples.samples;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MineralDetails1.
 
 <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MineralDetails1"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Abelsonite"/&gt;
 *     &lt;enumeration value="Abenakiite-(Ce)"/&gt;
 *     &lt;enumeration value="Abernathyite"/&gt;
 *     &lt;enumeration value="Abhurite"/&gt;
 *     &lt;enumeration value="Abswurmbachite"/&gt;
 *     &lt;enumeration value="Acanthite"/&gt;
 *     &lt;enumeration value="Acetamide"/&gt;
 *     &lt;enumeration value="Actinolite"/&gt;
 *     &lt;enumeration value="Acuminite"/&gt;
 *     &lt;enumeration value="Adamite"/&gt;
 *     &lt;enumeration value="Adamsite-(Y)"/&gt;
 *     &lt;enumeration value="Adelite"/&gt;
 *     &lt;enumeration value="Admontite"/&gt;
 *     &lt;enumeration value="Aegirine"/&gt;
 *     &lt;enumeration value="Aenigmatite"/&gt;
 *     &lt;enumeration value="Aerinite"/&gt;
 *     &lt;enumeration value="Aerugite"/&gt;
 *     &lt;enumeration value="Aeschynite"/&gt;
 *     &lt;enumeration value="Aeschynite-(Ce)"/&gt;
 *     &lt;enumeration value="Aeschynite-(Nd)"/&gt;
 *     &lt;enumeration value="Aeschynite-(Y)"/&gt;
 *     &lt;enumeration value="Afghanite"/&gt;
 *     &lt;enumeration value="Afwillite"/&gt;
 *     &lt;enumeration value="Agardite"/&gt;
 *     &lt;enumeration value="Agardite-(La)"/&gt;
 *     &lt;enumeration value="Agardite-(Y)"/&gt;
 *     &lt;enumeration value="Agrellite"/&gt;
 *     &lt;enumeration value="Agrinierite"/&gt;
 *     &lt;enumeration value="Aguilarite"/&gt;
 *     &lt;enumeration value="Aheylite"/&gt;
 *     &lt;enumeration value="Ahlfeldite"/&gt;
 *     &lt;enumeration value="Aikinite"/&gt;
 *     &lt;enumeration value="Ajoite"/&gt;
 *     &lt;enumeration value="Akaganeite"/&gt;
 *     &lt;enumeration value="Akatoreite"/&gt;
 *     &lt;enumeration value="Akdalaite"/&gt;
 *     &lt;enumeration value="Akermanite"/&gt;
 *     &lt;enumeration value="Akhtenskite"/&gt;
 *     &lt;enumeration value="Akimotoite"/&gt;
 *     &lt;enumeration value="Akrochordite"/&gt;
 *     &lt;enumeration value="Aksaite"/&gt;
 *     &lt;enumeration value="Aktashite"/&gt;
 *     &lt;enumeration value="Alabandite"/&gt;
 *     &lt;enumeration value="Alacranite"/&gt;
 *     &lt;enumeration value="Alamosite"/&gt;
 *     &lt;enumeration value="Alarsite"/&gt;
 *     &lt;enumeration value="Albite"/&gt;
 *     &lt;enumeration value="Albrechtschraufite"/&gt;
 *     &lt;enumeration value="Aldermanite"/&gt;
 *     &lt;enumeration value="Aldzhanite"/&gt;
 *     &lt;enumeration value="Aleksite"/&gt;
 *     &lt;enumeration value="Alforsite"/&gt;
 *     &lt;enumeration value="Algodonite"/&gt;
 *     &lt;enumeration value="Aliettite"/&gt;
 *     &lt;enumeration value="AllMinerals"/&gt;
 *     &lt;enumeration value="Allactite"/&gt;
 *     &lt;enumeration value="Allanite"/&gt;
 *     &lt;enumeration value="Allanite-(Ce)"/&gt;
 *     &lt;enumeration value="Allanite-(La)"/&gt;
 *     &lt;enumeration value="Allanite-(Y)"/&gt;
 *     &lt;enumeration value="Allargentum"/&gt;
 *     &lt;enumeration value="Alleghanyite"/&gt;
 *     &lt;enumeration value="Alloclasite"/&gt;
 *     &lt;enumeration value="Allophane"/&gt;
 *     &lt;enumeration value="Alluaivite"/&gt;
 *     &lt;enumeration value="Alluaudite"/&gt;
 *     &lt;enumeration value="Almandine"/&gt;
 *     &lt;enumeration value="Alstonite"/&gt;
 *     &lt;enumeration value="Altaite"/&gt;
 *     &lt;enumeration value="Althausite"/&gt;
 *     &lt;enumeration value="Althupite"/&gt;
 *     &lt;enumeration value="Altisite"/&gt;
 *     &lt;enumeration value="Alum(GeneralTerm)"/&gt;
 *     &lt;enumeration value="Aluminite"/&gt;
 *     &lt;enumeration value="Aluminium"/&gt;
 *     &lt;enumeration value="Aluminoceladonite"/&gt;
 *     &lt;enumeration value="Aluminocopiapite"/&gt;
 *     &lt;enumeration value="Aluminokatophorite"/&gt;
 *     &lt;enumeration value="Aluminotschermakite"/&gt;
 *     &lt;enumeration value="Aluminum"/&gt;
 *     &lt;enumeration value="Alumohydrocalcite"/&gt;
 *     &lt;enumeration value="Alumoklyuchevskite"/&gt;
 *     &lt;enumeration value="Alumopharmacosiderite"/&gt;
 *     &lt;enumeration value="Alumotantite"/&gt;
 *     &lt;enumeration value="Alumotungstite"/&gt;
 *     &lt;enumeration value="Alunite"/&gt;
 *     &lt;enumeration value="Alunogen"/&gt;
 *     &lt;enumeration value="Alvanite"/&gt;
 *     &lt;enumeration value="Amakinite"/&gt;
 *     &lt;enumeration value="Amalgam"/&gt;
 *     &lt;enumeration value="Amarantite"/&gt;
 *     &lt;enumeration value="Amarillite"/&gt;
 *     &lt;enumeration value="Amber"/&gt;
 *     &lt;enumeration value="Amblygonite"/&gt;
 *     &lt;enumeration value="Ameghinite"/&gt;
 *     &lt;enumeration value="Amesite"/&gt;
 *     &lt;enumeration value="Amicite"/&gt;
 *     &lt;enumeration value="Aminoffite"/&gt;
 *     &lt;enumeration value="Ammonioalunite"/&gt;
 *     &lt;enumeration value="Ammonioborite"/&gt;
 *     &lt;enumeration value="Ammoniojarosite"/&gt;
 *     &lt;enumeration value="Ammonioleucite"/&gt;
 *     &lt;enumeration value="AmphiboleGroup"/&gt;
 *     &lt;enumeration value="Amstallite"/&gt;
 *     &lt;enumeration value="Analcime"/&gt;
 *     &lt;enumeration value="Anandite"/&gt;
 *     &lt;enumeration value="Anapaite"/&gt;
 *     &lt;enumeration value="Anatase"/&gt;
 *     &lt;enumeration value="Ancylite-(Ce)"/&gt;
 *     &lt;enumeration value="Ancylite-(La)"/&gt;
 *     &lt;enumeration value="Andalusite"/&gt;
 *     &lt;enumeration value="Andersonite"/&gt;
 *     &lt;enumeration value="Andesine"/&gt;
 *     &lt;enumeration value="Andorite"/&gt;
 *     &lt;enumeration value="Andradite"/&gt;
 *     &lt;enumeration value="Andremeyerite"/&gt;
 *     &lt;enumeration value="Androsite-(La)"/&gt;
 *     &lt;enumeration value="Anduoite"/&gt;
 *     &lt;enumeration value="Angelellite"/&gt;
 *     &lt;enumeration value="Anglesite"/&gt;
 *     &lt;enumeration value="Anhydrite"/&gt;
 *     &lt;enumeration value="Anilite"/&gt;
 *     &lt;enumeration value="Ankangite"/&gt;
 *     &lt;enumeration value="Ankerite"/&gt;
 *     &lt;enumeration value="Annabergite"/&gt;
 *     &lt;enumeration value="Annite"/&gt;
 *     &lt;enumeration value="Anorthite"/&gt;
 *     &lt;enumeration value="Anorthoclase"/&gt;
 *     &lt;enumeration value="Antarcticite"/&gt;
 *     &lt;enumeration value="Anthoinite"/&gt;
 *     &lt;enumeration value="Anthonyite"/&gt;
 *     &lt;enumeration value="Anthophyllite"/&gt;
 *     &lt;enumeration value="Antigorite"/&gt;
 *     &lt;enumeration value="Antimonpearceite"/&gt;
 *     &lt;enumeration value="Antimonselite"/&gt;
 *     &lt;enumeration value="Antimony"/&gt;
 *     &lt;enumeration value="Antlerite"/&gt;
 *     &lt;enumeration value="Anyuiite"/&gt;
 *     &lt;enumeration value="Apachite"/&gt;
 *     &lt;enumeration value="ApatiteGroup"/&gt;
 *     &lt;enumeration value="Aphthitalite"/&gt;
 *     &lt;enumeration value="Apjohnite"/&gt;
 *     &lt;enumeration value="Aplowite"/&gt;
 *     &lt;enumeration value="Apophyllite"/&gt;
 *     &lt;enumeration value="Apuanite"/&gt;
 *     &lt;enumeration value="Aragonite"/&gt;
 *     &lt;enumeration value="Arakiite"/&gt;
 *     &lt;enumeration value="Aramayoite"/&gt;
 *     &lt;enumeration value="Aravaipaite"/&gt;
 *     &lt;enumeration value="Arcanite"/&gt;
 *     &lt;enumeration value="Archerite"/&gt;
 *     &lt;enumeration value="Arctite"/&gt;
 *     &lt;enumeration value="Arcubisite"/&gt;
 *     &lt;enumeration value="Ardaite"/&gt;
 *     &lt;enumeration value="Ardealite"/&gt;
 *     &lt;enumeration value="Ardennite"/&gt;
 *     &lt;enumeration value="Arfvedsonite"/&gt;
 *     &lt;enumeration value="Argentojarosite"/&gt;
 *     &lt;enumeration value="Argentopentlandite"/&gt;
 *     &lt;enumeration value="Argentopyrite"/&gt;
 *     &lt;enumeration value="Argentotennantite"/&gt;
 *     &lt;enumeration value="Argutite"/&gt;
 *     &lt;enumeration value="Argyrodite"/&gt;
 *     &lt;enumeration value="Arhbarite"/&gt;
 *     &lt;enumeration value="Aristarainite"/&gt;
 *     &lt;enumeration value="Armalcolite"/&gt;
 *     &lt;enumeration value="Armangite"/&gt;
 *     &lt;enumeration value="Armenite"/&gt;
 *     &lt;enumeration value="Armstrongite"/&gt;
 *     &lt;enumeration value="Arnhemite"/&gt;
 *     &lt;enumeration value="Arrojadite"/&gt;
 *     &lt;enumeration value="Arsenbrackebuschite"/&gt;
 *     &lt;enumeration value="Arsendescloizite"/&gt;
 *     &lt;enumeration value="Arsenic"/&gt;
 *     &lt;enumeration value="Arseniopleite"/&gt;
 *     &lt;enumeration value="Arseniosiderite"/&gt;
 *     &lt;enumeration value="Arsenobismite"/&gt;
 *     &lt;enumeration value="Arsenoclasite"/&gt;
 *     &lt;enumeration value="Arsenocrandallite"/&gt;
 *     &lt;enumeration value="Arsenoflorencite-(Ce)"/&gt;
 *     &lt;enumeration value="Arsenogorceixite"/&gt;
 *     &lt;enumeration value="Arsenogoyazite"/&gt;
 *     &lt;enumeration value="Arsenohauchecornite"/&gt;
 *     &lt;enumeration value="Arsenolamprite"/&gt;
 *     &lt;enumeration value="Arsenolite"/&gt;
 *     &lt;enumeration value="Arsenopalladinite"/&gt;
 *     &lt;enumeration value="Arsenopyrite"/&gt;
 *     &lt;enumeration value="Arsenosulvanite"/&gt;
 *     &lt;enumeration value="Arsenpolybasite"/&gt;
 *     &lt;enumeration value="Arsentsumebite"/&gt;
 *     &lt;enumeration value="Arsenuranospathite"/&gt;
 *     &lt;enumeration value="Arsenuranylite"/&gt;
 *     &lt;enumeration value="Arthurite"/&gt;
 *     &lt;enumeration value="Artinite"/&gt;
 *     &lt;enumeration value="Artroeite"/&gt;
 *     &lt;enumeration value="Arupite"/&gt;
 *     &lt;enumeration value="Arzakite"/&gt;
 *     &lt;enumeration value="Asbecasite"/&gt;
 *     &lt;enumeration value="Asbestos"/&gt;
 *     &lt;enumeration value="Asbolane"/&gt;
 *     &lt;enumeration value="Aschamalmite"/&gt;
 *     &lt;enumeration value="Ashanite"/&gt;
 *     &lt;enumeration value="Ashburtonite"/&gt;
 *     &lt;enumeration value="Ashcroftine-(Y)"/&gt;
 *     &lt;enumeration value="Ashoverite"/&gt;
 *     &lt;enumeration value="Asisite"/&gt;
 *     &lt;enumeration value="Aspidolite"/&gt;
 *     &lt;enumeration value="Asselbornite"/&gt;
 *     &lt;enumeration value="Astrocyanite-(Ce)"/&gt;
 *     &lt;enumeration value="Astrophyllite"/&gt;
 *     &lt;enumeration value="Atacamite"/&gt;
 *     &lt;enumeration value="Atelestite"/&gt;
 *     &lt;enumeration value="Athabascaite"/&gt;
 *     &lt;enumeration value="Atheneite"/&gt;
 *     &lt;enumeration value="Atlasovite"/&gt;
 *     &lt;enumeration value="Atokite"/&gt;
 *     &lt;enumeration value="Attakolite"/&gt;
 *     &lt;enumeration value="Aubertite"/&gt;
 *     &lt;enumeration value="Augelite"/&gt;
 *     &lt;enumeration value="Augite"/&gt;
 *     &lt;enumeration value="Aurantimonate"/&gt;
 *     &lt;enumeration value="Aurichalcite"/&gt;
 *     &lt;enumeration value="Auricupride"/&gt;
 *     &lt;enumeration value="Aurorite"/&gt;
 *     &lt;enumeration value="Aurostibite"/&gt;
 *     &lt;enumeration value="Austinite"/&gt;
 *     &lt;enumeration value="Autunite"/&gt;
 *     &lt;enumeration value="Averievite"/&gt;
 *     &lt;enumeration value="Avicennite"/&gt;
 *     &lt;enumeration value="Avogadrite"/&gt;
 *     &lt;enumeration value="Awaruite"/&gt;
 *     &lt;enumeration value="Azoproite"/&gt;
 *     &lt;enumeration value="Azurite"/&gt;
 *     &lt;enumeration value="Babefphite"/&gt;
 *     &lt;enumeration value="Babingtonite"/&gt;
 *     &lt;enumeration value="Babkinite"/&gt;
 *     &lt;enumeration value="Baddeleyite"/&gt;
 *     &lt;enumeration value="Bafertisite"/&gt;
 *     &lt;enumeration value="Baghdadite"/&gt;
 *     &lt;enumeration value="Bahianite"/&gt;
 *     &lt;enumeration value="Baileychlore"/&gt;
 *     &lt;enumeration value="Baiyuneboite"/&gt;
 *     &lt;enumeration value="Baiyuneboite-(Ce)"/&gt;
 *     &lt;enumeration value="Bakerite"/&gt;
 *     &lt;enumeration value="Bakhchisaraitsevite"/&gt;
 *     &lt;enumeration value="Baksanite"/&gt;
 *     &lt;enumeration value="Balangeroite"/&gt;
 *     &lt;enumeration value="Balavinskite"/&gt;
 *     &lt;enumeration value="Balipholite"/&gt;
 *     &lt;enumeration value="Balkanite"/&gt;
 *     &lt;enumeration value="Balyakinite"/&gt;
 *     &lt;enumeration value="Bambollaite"/&gt;
 *     &lt;enumeration value="Bamfordite"/&gt;
 *     &lt;enumeration value="Banalsite"/&gt;
 *     &lt;enumeration value="Bandylite"/&gt;
 *     &lt;enumeration value="Bannermanite"/&gt;
 *     &lt;enumeration value="Bannisterite"/&gt;
 *     &lt;enumeration value="Baotite"/&gt;
 *     &lt;enumeration value="Bararite"/&gt;
 *     &lt;enumeration value="Baratovite"/&gt;
 *     &lt;enumeration value="Barberiite"/&gt;
 *     &lt;enumeration value="Barbertonite"/&gt;
 *     &lt;enumeration value="Barbosalite"/&gt;
 *     &lt;enumeration value="Barentsite"/&gt;
 *     &lt;enumeration value="Bariandite"/&gt;
 *     &lt;enumeration value="Baricite"/&gt;
 *     &lt;enumeration value="Bario-orthojoaquinite"/&gt;
 *     &lt;enumeration value="Bariomicrolite"/&gt;
 *     &lt;enumeration value="Bariopyrochlore"/&gt;
 *     &lt;enumeration value="Bariosincosite"/&gt;
 *     &lt;enumeration value="Barite"/&gt;
 *     &lt;enumeration value="Barium-pharmacosiderite"/&gt;
 *     &lt;enumeration value="Barnesite"/&gt;
 *     &lt;enumeration value="Barquillite"/&gt;
 *     &lt;enumeration value="Barrerite"/&gt;
 *     &lt;enumeration value="Barringerite"/&gt;
 *     &lt;enumeration value="Barringtonite"/&gt;
 *     &lt;enumeration value="Barroisite"/&gt;
 *     &lt;enumeration value="Barstowite"/&gt;
 *     &lt;enumeration value="Bartelkeite"/&gt;
 *     &lt;enumeration value="Bartonite"/&gt;
 *     &lt;enumeration value="Barylite"/&gt;
 *     &lt;enumeration value="Barysilite"/&gt;
 *     &lt;enumeration value="Barytocalcite"/&gt;
 *     &lt;enumeration value="Barytolamprophyllite"/&gt;
 *     &lt;enumeration value="Basaluminite"/&gt;
 *     &lt;enumeration value="Bassanite"/&gt;
 *     &lt;enumeration value="Bassetite"/&gt;
 *     &lt;enumeration value="Bastnasite"/&gt;
 *     &lt;enumeration value="Bastnasite-(Ce)"/&gt;
 *     &lt;enumeration value="Bastnasite-(La)"/&gt;
 *     &lt;enumeration value="Bastnasite-(Y)"/&gt;
 *     &lt;enumeration value="Batiferrite"/&gt;
 *     &lt;enumeration value="Batisite"/&gt;
 *     &lt;enumeration value="Baumhauerite"/&gt;
 *     &lt;enumeration value="Baumhauerite-2a"/&gt;
 *     &lt;enumeration value="Baumite"/&gt;
 *     &lt;enumeration value="Baumstarkite"/&gt;
 *     &lt;enumeration value="Bauranoite"/&gt;
 *     &lt;enumeration value="Bauxite(GeneralTerm)"/&gt;
 *     &lt;enumeration value="Bavenite"/&gt;
 *     &lt;enumeration value="Bayankhanite"/&gt;
 *     &lt;enumeration value="Bayerite"/&gt;
 *     &lt;enumeration value="Bayldonite"/&gt;
 *     &lt;enumeration value="Bayleyite"/&gt;
 *     &lt;enumeration value="Baylissite"/&gt;
 *     &lt;enumeration value="Bazhenovite"/&gt;
 *     &lt;enumeration value="Bazirite"/&gt;
 *     &lt;enumeration value="Bazzite"/&gt;
 *     &lt;enumeration value="Bearsite"/&gt;
 *     &lt;enumeration value="Bearthite"/&gt;
 *     &lt;enumeration value="Beaverite"/&gt;
 *     &lt;enumeration value="Bechererite"/&gt;
 *     &lt;enumeration value="Becquerelite"/&gt;
 *     &lt;enumeration value="Bederite"/&gt;
 *     &lt;enumeration value="Behierite"/&gt;
 *     &lt;enumeration value="Behoite"/&gt;
 *     &lt;enumeration value="Beidellite"/&gt;
 *     &lt;enumeration value="Belendorffite"/&gt;
 *     &lt;enumeration value="Belkovite"/&gt;
 *     &lt;enumeration value="Bellbergite"/&gt;
 *     &lt;enumeration value="Bellidoite"/&gt;
 *     &lt;enumeration value="Bellingerite"/&gt;
 *     &lt;enumeration value="Belloite"/&gt;
 *     &lt;enumeration value="Belovite-(Ce)"/&gt;
 *     &lt;enumeration value="Belovite-(La)"/&gt;
 *     &lt;enumeration value="Belyankinite"/&gt;
 *     &lt;enumeration value="Bementite"/&gt;
 *     &lt;enumeration value="Benauite"/&gt;
 *     &lt;enumeration value="Benavidesite"/&gt;
 *     &lt;enumeration value="Benitoite"/&gt;
 *     &lt;enumeration value="Benjaminite"/&gt;
 *     &lt;enumeration value="Benleonardite"/&gt;
 *     &lt;enumeration value="Benstonite"/&gt;
 *     &lt;enumeration value="Bentorite"/&gt;
 *     &lt;enumeration value="Benyacarite"/&gt;
 *     &lt;enumeration value="Beraunite"/&gt;
 *     &lt;enumeration value="Berborite"/&gt;
 *     &lt;enumeration value="Berborite-1t"/&gt;
 *     &lt;enumeration value="Berdesinskiite"/&gt;
 *     &lt;enumeration value="Berezanskite"/&gt;
 *     &lt;enumeration value="Bergenite"/&gt;
 *     &lt;enumeration value="Bergslagite"/&gt;
 *     &lt;enumeration value="Berlinite"/&gt;
 *     &lt;enumeration value="Bermanite"/&gt;
 *     &lt;enumeration value="Bernalite"/&gt;
 *     &lt;enumeration value="Bernardite"/&gt;
 *     &lt;enumeration value="Berndtite"/&gt;
 *     &lt;enumeration value="Berndtite-2t"/&gt;
 *     &lt;enumeration value="Berndtite-4h"/&gt;
 *     &lt;enumeration value="Berryite"/&gt;
 *     &lt;enumeration value="Berthierine"/&gt;
 *     &lt;enumeration value="Berthierite"/&gt;
 *     &lt;enumeration value="Bertossaite"/&gt;
 *     &lt;enumeration value="Bertrandite"/&gt;
 *     &lt;enumeration value="Beryl"/&gt;
 *     &lt;enumeration value="Beryllite"/&gt;
 *     &lt;enumeration value="Beryllonite"/&gt;
 *     &lt;enumeration value="Berzelianite"/&gt;
 *     &lt;enumeration value="Berzeliite"/&gt;
 *     &lt;enumeration value="Bessmertnovite"/&gt;
 *     &lt;enumeration value="Beta-fergusonite-(Ce)"/&gt;
 *     &lt;enumeration value="Beta-fergusonite-(Nd)"/&gt;
 *     &lt;enumeration value="Beta-fergusonite-(Y)"/&gt;
 *     &lt;enumeration value="Betafite"/&gt;
 *     &lt;enumeration value="Betekhtinite"/&gt;
 *     &lt;enumeration value="Betpakdalite"/&gt;
 *     &lt;enumeration value="Beudantite"/&gt;
 *     &lt;enumeration value="Beusite"/&gt;
 *     &lt;enumeration value="Beyerite"/&gt;
 *     &lt;enumeration value="Bezsmertnovite"/&gt;
 *     &lt;enumeration value="Bianchite"/&gt;
 *     &lt;enumeration value="Bicchulite"/&gt;
 *     &lt;enumeration value="Bideauxite"/&gt;
 *     &lt;enumeration value="Bieberite"/&gt;
 *     &lt;enumeration value="Biehlite"/&gt;
 *     &lt;enumeration value="Bigcreekite"/&gt;
 *     &lt;enumeration value="Bijvoetite-(Y)"/&gt;
 *     &lt;enumeration value="Bikitaite"/&gt;
 *     &lt;enumeration value="Bilibinskite"/&gt;
 *     &lt;enumeration value="Bilinite"/&gt;
 *     &lt;enumeration value="Billietite"/&gt;
 *     &lt;enumeration value="Billingsleyite"/&gt;
 *     &lt;enumeration value="Bindheimite"/&gt;
 *     &lt;enumeration value="Biotite"/&gt;
 *     &lt;enumeration value="Biphosphammite"/&gt;
 *     &lt;enumeration value="Biringuccite"/&gt;
 *     &lt;enumeration value="Birnessite"/&gt;
 *     &lt;enumeration value="Bischofite"/&gt;
 *     &lt;enumeration value="Bismite"/&gt;
 *     &lt;enumeration value="Bismoclite"/&gt;
 *     &lt;enumeration value="Bismuth"/&gt;
 *     &lt;enumeration value="Bismuthinite"/&gt;
 *     &lt;enumeration value="Bismutite"/&gt;
 *     &lt;enumeration value="Bismutocolumbite"/&gt;
 *     &lt;enumeration value="Bismutoferrite"/&gt;
 *     &lt;enumeration value="Bismutohauchecornite"/&gt;
 *     &lt;enumeration value="Bismutomicrolite"/&gt;
 *     &lt;enumeration value="Bismutopyrochlore"/&gt;
 *     &lt;enumeration value="Bismutostibiconite"/&gt;
 *     &lt;enumeration value="Bismutotantalite"/&gt;
 *     &lt;enumeration value="Bityite"/&gt;
 *     &lt;enumeration value="Bixbyite"/&gt;
 *     &lt;enumeration value="Bjarebyite"/&gt;
 *     &lt;enumeration value="Blakeite"/&gt;
 *     &lt;enumeration value="Blatonite"/&gt;
 *     &lt;enumeration value="Blatterite"/&gt;
 *     &lt;enumeration value="Bleasdaleite"/&gt;
 *     &lt;enumeration value="Blixite"/&gt;
 *     &lt;enumeration value="Blodite"/&gt;
 *     &lt;enumeration value="Blossite"/&gt;
 *     &lt;enumeration value="Bobfergusonite"/&gt;
 *     &lt;enumeration value="Bobierrite"/&gt;
 *     &lt;enumeration value="Bogdanovite"/&gt;
 *     &lt;enumeration value="Boggildite"/&gt;
 *     &lt;enumeration value="Boggsite"/&gt;
 *     &lt;enumeration value="Bogvadite"/&gt;
 *     &lt;enumeration value="Bohdanowiczite"/&gt;
 *     &lt;enumeration value="Bohmite"/&gt;
 *     &lt;enumeration value="Bokite"/&gt;
 *     &lt;enumeration value="Boleite"/&gt;
 *     &lt;enumeration value="Bolivarite"/&gt;
 *     &lt;enumeration value="Boltwoodite"/&gt;
 *     &lt;enumeration value="Bonaccordite"/&gt;
 *     &lt;enumeration value="Bonattite"/&gt;
 *     &lt;enumeration value="Bonshtedtite"/&gt;
 *     &lt;enumeration value="Boothite"/&gt;
 *     &lt;enumeration value="Boracite"/&gt;
 *     &lt;enumeration value="Boralsilite"/&gt;
 *     &lt;enumeration value="Borax"/&gt;
 *     &lt;enumeration value="Borcarite"/&gt;
 *     &lt;enumeration value="Borishanskiite"/&gt;
 *     &lt;enumeration value="Bornemanite"/&gt;
 *     &lt;enumeration value="Bornhardtite"/&gt;
 *     &lt;enumeration value="Bornite"/&gt;
 *     &lt;enumeration value="Borodaevite"/&gt;
 *     &lt;enumeration value="Boromuscovite"/&gt;
 *     &lt;enumeration value="Borovskite"/&gt;
 *     &lt;enumeration value="Bostwickite"/&gt;
 *     &lt;enumeration value="Botallackite"/&gt;
 *     &lt;enumeration value="Botryogen"/&gt;
 *     &lt;enumeration value="Bottinoite"/&gt;
 *     &lt;enumeration value="Boulangerite"/&gt;
 *     &lt;enumeration value="Bournonite"/&gt;
 *     &lt;enumeration value="Boussingaultite"/&gt;
 *     &lt;enumeration value="Boussingualtite"/&gt;
 *     &lt;enumeration value="Bowieite"/&gt;
 *     &lt;enumeration value="Boyleite"/&gt;
 *     &lt;enumeration value="Brabantite"/&gt;
 *     &lt;enumeration value="Bracewellite"/&gt;
 *     &lt;enumeration value="Brackebuschite"/&gt;
 *     &lt;enumeration value="Bradleyite"/&gt;
 *     &lt;enumeration value="Braggite"/&gt;
 *     &lt;enumeration value="Braitschite-(Ce)"/&gt;
 *     &lt;enumeration value="Brammallite"/&gt;
 *     &lt;enumeration value="Brandholzite"/&gt;
 *     &lt;enumeration value="Brandtite"/&gt;
 *     &lt;enumeration value="Brannerite"/&gt;
 *     &lt;enumeration value="Brannockite"/&gt;
 *     &lt;enumeration value="Brassite"/&gt;
 *     &lt;enumeration value="Braunite"/&gt;
 *     &lt;enumeration value="Bravoite"/&gt;
 *     &lt;enumeration value="Brazilianite"/&gt;
 *     &lt;enumeration value="Bredigite"/&gt;
 *     &lt;enumeration value="Breithauptite"/&gt;
 *     &lt;enumeration value="Brenkite"/&gt;
 *     &lt;enumeration value="Brewsterite"/&gt;
 *     &lt;enumeration value="Brewsterite-Ba"/&gt;
 *     &lt;enumeration value="Brewsterite-Sr"/&gt;
 *     &lt;enumeration value="Brezinaite"/&gt;
 *     &lt;enumeration value="Brianite"/&gt;
 *     &lt;enumeration value="Brianroulstonite"/&gt;
 *     &lt;enumeration value="Brianyoungite"/&gt;
 *     &lt;enumeration value="Briartite"/&gt;
 *     &lt;enumeration value="Brindleyite"/&gt;
 *     &lt;enumeration value="Britholite"/&gt;
 *     &lt;enumeration value="Britholite-(Ce)"/&gt;
 *     &lt;enumeration value="Britholite-(Y)"/&gt;
 *     &lt;enumeration value="Brizziite"/&gt;
 *     &lt;enumeration value="Brochantite"/&gt;
 *     &lt;enumeration value="Brockite"/&gt;
 *     &lt;enumeration value="Brokenhillite"/&gt;
 *     &lt;enumeration value="Bromargyrite"/&gt;
 *     &lt;enumeration value="Bromellite"/&gt;
 *     &lt;enumeration value="Brookite"/&gt;
 *     &lt;enumeration value="Brownmillerite"/&gt;
 *     &lt;enumeration value="Brucite"/&gt;
 *     &lt;enumeration value="Bruggenite"/&gt;
 *     &lt;enumeration value="Brugnatellite"/&gt;
 *     &lt;enumeration value="Brunogeierite"/&gt;
 *     &lt;enumeration value="Brushite"/&gt;
 *     &lt;enumeration value="Buchwaldite"/&gt;
 *     &lt;enumeration value="Buckhornite"/&gt;
 *     &lt;enumeration value="Buddingtonite"/&gt;
 *     &lt;enumeration value="Buergerite"/&gt;
 *     &lt;enumeration value="Buetschliite"/&gt;
 *     &lt;enumeration value="Bukovite"/&gt;
 *     &lt;enumeration value="Bukovskyite"/&gt;
 *     &lt;enumeration value="Bulachite"/&gt;
 *     &lt;enumeration value="Bultfonteinite"/&gt;
 *     &lt;enumeration value="Bunsenite"/&gt;
 *     &lt;enumeration value="Burangaite"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MineralDetails", namespace = "http://app.geosamples.org")
@XmlEnum
public enum MineralDetails1 {

    @XmlEnumValue("Abelsonite")
    ABELSONITE("Abelsonite"),
    @XmlEnumValue("Abenakiite-(Ce)")
    ABENAKIITE_CE("Abenakiite-(Ce)"),
    @XmlEnumValue("Abernathyite")
    ABERNATHYITE("Abernathyite"),
    @XmlEnumValue("Abhurite")
    ABHURITE("Abhurite"),
    @XmlEnumValue("Abswurmbachite")
    ABSWURMBACHITE("Abswurmbachite"),
    @XmlEnumValue("Acanthite")
    ACANTHITE("Acanthite"),
    @XmlEnumValue("Acetamide")
    ACETAMIDE("Acetamide"),
    @XmlEnumValue("Actinolite")
    ACTINOLITE("Actinolite"),
    @XmlEnumValue("Acuminite")
    ACUMINITE("Acuminite"),
    @XmlEnumValue("Adamite")
    ADAMITE("Adamite"),
    @XmlEnumValue("Adamsite-(Y)")
    ADAMSITE_Y("Adamsite-(Y)"),
    @XmlEnumValue("Adelite")
    ADELITE("Adelite"),
    @XmlEnumValue("Admontite")
    ADMONTITE("Admontite"),
    @XmlEnumValue("Aegirine")
    AEGIRINE("Aegirine"),
    @XmlEnumValue("Aenigmatite")
    AENIGMATITE("Aenigmatite"),
    @XmlEnumValue("Aerinite")
    AERINITE("Aerinite"),
    @XmlEnumValue("Aerugite")
    AERUGITE("Aerugite"),
    @XmlEnumValue("Aeschynite")
    AESCHYNITE("Aeschynite"),
    @XmlEnumValue("Aeschynite-(Ce)")
    AESCHYNITE_CE("Aeschynite-(Ce)"),
    @XmlEnumValue("Aeschynite-(Nd)")
    AESCHYNITE_ND("Aeschynite-(Nd)"),
    @XmlEnumValue("Aeschynite-(Y)")
    AESCHYNITE_Y("Aeschynite-(Y)"),
    @XmlEnumValue("Afghanite")
    AFGHANITE("Afghanite"),
    @XmlEnumValue("Afwillite")
    AFWILLITE("Afwillite"),
    @XmlEnumValue("Agardite")
    AGARDITE("Agardite"),
    @XmlEnumValue("Agardite-(La)")
    AGARDITE_LA("Agardite-(La)"),
    @XmlEnumValue("Agardite-(Y)")
    AGARDITE_Y("Agardite-(Y)"),
    @XmlEnumValue("Agrellite")
    AGRELLITE("Agrellite"),
    @XmlEnumValue("Agrinierite")
    AGRINIERITE("Agrinierite"),
    @XmlEnumValue("Aguilarite")
    AGUILARITE("Aguilarite"),
    @XmlEnumValue("Aheylite")
    AHEYLITE("Aheylite"),
    @XmlEnumValue("Ahlfeldite")
    AHLFELDITE("Ahlfeldite"),
    @XmlEnumValue("Aikinite")
    AIKINITE("Aikinite"),
    @XmlEnumValue("Ajoite")
    AJOITE("Ajoite"),
    @XmlEnumValue("Akaganeite")
    AKAGANEITE("Akaganeite"),
    @XmlEnumValue("Akatoreite")
    AKATOREITE("Akatoreite"),
    @XmlEnumValue("Akdalaite")
    AKDALAITE("Akdalaite"),
    @XmlEnumValue("Akermanite")
    AKERMANITE("Akermanite"),
    @XmlEnumValue("Akhtenskite")
    AKHTENSKITE("Akhtenskite"),
    @XmlEnumValue("Akimotoite")
    AKIMOTOITE("Akimotoite"),
    @XmlEnumValue("Akrochordite")
    AKROCHORDITE("Akrochordite"),
    @XmlEnumValue("Aksaite")
    AKSAITE("Aksaite"),
    @XmlEnumValue("Aktashite")
    AKTASHITE("Aktashite"),
    @XmlEnumValue("Alabandite")
    ALABANDITE("Alabandite"),
    @XmlEnumValue("Alacranite")
    ALACRANITE("Alacranite"),
    @XmlEnumValue("Alamosite")
    ALAMOSITE("Alamosite"),
    @XmlEnumValue("Alarsite")
    ALARSITE("Alarsite"),
    @XmlEnumValue("Albite")
    ALBITE("Albite"),
    @XmlEnumValue("Albrechtschraufite")
    ALBRECHTSCHRAUFITE("Albrechtschraufite"),
    @XmlEnumValue("Aldermanite")
    ALDERMANITE("Aldermanite"),
    @XmlEnumValue("Aldzhanite")
    ALDZHANITE("Aldzhanite"),
    @XmlEnumValue("Aleksite")
    ALEKSITE("Aleksite"),
    @XmlEnumValue("Alforsite")
    ALFORSITE("Alforsite"),
    @XmlEnumValue("Algodonite")
    ALGODONITE("Algodonite"),
    @XmlEnumValue("Aliettite")
    ALIETTITE("Aliettite"),
    @XmlEnumValue("AllMinerals")
    ALL_MINERALS("AllMinerals"),
    @XmlEnumValue("Allactite")
    ALLACTITE("Allactite"),
    @XmlEnumValue("Allanite")
    ALLANITE("Allanite"),
    @XmlEnumValue("Allanite-(Ce)")
    ALLANITE_CE("Allanite-(Ce)"),
    @XmlEnumValue("Allanite-(La)")
    ALLANITE_LA("Allanite-(La)"),
    @XmlEnumValue("Allanite-(Y)")
    ALLANITE_Y("Allanite-(Y)"),
    @XmlEnumValue("Allargentum")
    ALLARGENTUM("Allargentum"),
    @XmlEnumValue("Alleghanyite")
    ALLEGHANYITE("Alleghanyite"),
    @XmlEnumValue("Alloclasite")
    ALLOCLASITE("Alloclasite"),
    @XmlEnumValue("Allophane")
    ALLOPHANE("Allophane"),
    @XmlEnumValue("Alluaivite")
    ALLUAIVITE("Alluaivite"),
    @XmlEnumValue("Alluaudite")
    ALLUAUDITE("Alluaudite"),
    @XmlEnumValue("Almandine")
    ALMANDINE("Almandine"),
    @XmlEnumValue("Alstonite")
    ALSTONITE("Alstonite"),
    @XmlEnumValue("Altaite")
    ALTAITE("Altaite"),
    @XmlEnumValue("Althausite")
    ALTHAUSITE("Althausite"),
    @XmlEnumValue("Althupite")
    ALTHUPITE("Althupite"),
    @XmlEnumValue("Altisite")
    ALTISITE("Altisite"),
    @XmlEnumValue("Alum(GeneralTerm)")
    ALUM_GENERAL_TERM("Alum(GeneralTerm)"),
    @XmlEnumValue("Aluminite")
    ALUMINITE("Aluminite"),
    @XmlEnumValue("Aluminium")
    ALUMINIUM("Aluminium"),
    @XmlEnumValue("Aluminoceladonite")
    ALUMINOCELADONITE("Aluminoceladonite"),
    @XmlEnumValue("Aluminocopiapite")
    ALUMINOCOPIAPITE("Aluminocopiapite"),
    @XmlEnumValue("Aluminokatophorite")
    ALUMINOKATOPHORITE("Aluminokatophorite"),
    @XmlEnumValue("Aluminotschermakite")
    ALUMINOTSCHERMAKITE("Aluminotschermakite"),
    @XmlEnumValue("Aluminum")
    ALUMINUM("Aluminum"),
    @XmlEnumValue("Alumohydrocalcite")
    ALUMOHYDROCALCITE("Alumohydrocalcite"),
    @XmlEnumValue("Alumoklyuchevskite")
    ALUMOKLYUCHEVSKITE("Alumoklyuchevskite"),
    @XmlEnumValue("Alumopharmacosiderite")
    ALUMOPHARMACOSIDERITE("Alumopharmacosiderite"),
    @XmlEnumValue("Alumotantite")
    ALUMOTANTITE("Alumotantite"),
    @XmlEnumValue("Alumotungstite")
    ALUMOTUNGSTITE("Alumotungstite"),
    @XmlEnumValue("Alunite")
    ALUNITE("Alunite"),
    @XmlEnumValue("Alunogen")
    ALUNOGEN("Alunogen"),
    @XmlEnumValue("Alvanite")
    ALVANITE("Alvanite"),
    @XmlEnumValue("Amakinite")
    AMAKINITE("Amakinite"),
    @XmlEnumValue("Amalgam")
    AMALGAM("Amalgam"),
    @XmlEnumValue("Amarantite")
    AMARANTITE("Amarantite"),
    @XmlEnumValue("Amarillite")
    AMARILLITE("Amarillite"),
    @XmlEnumValue("Amber")
    AMBER("Amber"),
    @XmlEnumValue("Amblygonite")
    AMBLYGONITE("Amblygonite"),
    @XmlEnumValue("Ameghinite")
    AMEGHINITE("Ameghinite"),
    @XmlEnumValue("Amesite")
    AMESITE("Amesite"),
    @XmlEnumValue("Amicite")
    AMICITE("Amicite"),
    @XmlEnumValue("Aminoffite")
    AMINOFFITE("Aminoffite"),
    @XmlEnumValue("Ammonioalunite")
    AMMONIOALUNITE("Ammonioalunite"),
    @XmlEnumValue("Ammonioborite")
    AMMONIOBORITE("Ammonioborite"),
    @XmlEnumValue("Ammoniojarosite")
    AMMONIOJAROSITE("Ammoniojarosite"),
    @XmlEnumValue("Ammonioleucite")
    AMMONIOLEUCITE("Ammonioleucite"),
    @XmlEnumValue("AmphiboleGroup")
    AMPHIBOLE_GROUP("AmphiboleGroup"),
    @XmlEnumValue("Amstallite")
    AMSTALLITE("Amstallite"),
    @XmlEnumValue("Analcime")
    ANALCIME("Analcime"),
    @XmlEnumValue("Anandite")
    ANANDITE("Anandite"),
    @XmlEnumValue("Anapaite")
    ANAPAITE("Anapaite"),
    @XmlEnumValue("Anatase")
    ANATASE("Anatase"),
    @XmlEnumValue("Ancylite-(Ce)")
    ANCYLITE_CE("Ancylite-(Ce)"),
    @XmlEnumValue("Ancylite-(La)")
    ANCYLITE_LA("Ancylite-(La)"),
    @XmlEnumValue("Andalusite")
    ANDALUSITE("Andalusite"),
    @XmlEnumValue("Andersonite")
    ANDERSONITE("Andersonite"),
    @XmlEnumValue("Andesine")
    ANDESINE("Andesine"),
    @XmlEnumValue("Andorite")
    ANDORITE("Andorite"),
    @XmlEnumValue("Andradite")
    ANDRADITE("Andradite"),
    @XmlEnumValue("Andremeyerite")
    ANDREMEYERITE("Andremeyerite"),
    @XmlEnumValue("Androsite-(La)")
    ANDROSITE_LA("Androsite-(La)"),
    @XmlEnumValue("Anduoite")
    ANDUOITE("Anduoite"),
    @XmlEnumValue("Angelellite")
    ANGELELLITE("Angelellite"),
    @XmlEnumValue("Anglesite")
    ANGLESITE("Anglesite"),
    @XmlEnumValue("Anhydrite")
    ANHYDRITE("Anhydrite"),
    @XmlEnumValue("Anilite")
    ANILITE("Anilite"),
    @XmlEnumValue("Ankangite")
    ANKANGITE("Ankangite"),
    @XmlEnumValue("Ankerite")
    ANKERITE("Ankerite"),
    @XmlEnumValue("Annabergite")
    ANNABERGITE("Annabergite"),
    @XmlEnumValue("Annite")
    ANNITE("Annite"),
    @XmlEnumValue("Anorthite")
    ANORTHITE("Anorthite"),
    @XmlEnumValue("Anorthoclase")
    ANORTHOCLASE("Anorthoclase"),
    @XmlEnumValue("Antarcticite")
    ANTARCTICITE("Antarcticite"),
    @XmlEnumValue("Anthoinite")
    ANTHOINITE("Anthoinite"),
    @XmlEnumValue("Anthonyite")
    ANTHONYITE("Anthonyite"),
    @XmlEnumValue("Anthophyllite")
    ANTHOPHYLLITE("Anthophyllite"),
    @XmlEnumValue("Antigorite")
    ANTIGORITE("Antigorite"),
    @XmlEnumValue("Antimonpearceite")
    ANTIMONPEARCEITE("Antimonpearceite"),
    @XmlEnumValue("Antimonselite")
    ANTIMONSELITE("Antimonselite"),
    @XmlEnumValue("Antimony")
    ANTIMONY("Antimony"),
    @XmlEnumValue("Antlerite")
    ANTLERITE("Antlerite"),
    @XmlEnumValue("Anyuiite")
    ANYUIITE("Anyuiite"),
    @XmlEnumValue("Apachite")
    APACHITE("Apachite"),
    @XmlEnumValue("ApatiteGroup")
    APATITE_GROUP("ApatiteGroup"),
    @XmlEnumValue("Aphthitalite")
    APHTHITALITE("Aphthitalite"),
    @XmlEnumValue("Apjohnite")
    APJOHNITE("Apjohnite"),
    @XmlEnumValue("Aplowite")
    APLOWITE("Aplowite"),
    @XmlEnumValue("Apophyllite")
    APOPHYLLITE("Apophyllite"),
    @XmlEnumValue("Apuanite")
    APUANITE("Apuanite"),
    @XmlEnumValue("Aragonite")
    ARAGONITE("Aragonite"),
    @XmlEnumValue("Arakiite")
    ARAKIITE("Arakiite"),
    @XmlEnumValue("Aramayoite")
    ARAMAYOITE("Aramayoite"),
    @XmlEnumValue("Aravaipaite")
    ARAVAIPAITE("Aravaipaite"),
    @XmlEnumValue("Arcanite")
    ARCANITE("Arcanite"),
    @XmlEnumValue("Archerite")
    ARCHERITE("Archerite"),
    @XmlEnumValue("Arctite")
    ARCTITE("Arctite"),
    @XmlEnumValue("Arcubisite")
    ARCUBISITE("Arcubisite"),
    @XmlEnumValue("Ardaite")
    ARDAITE("Ardaite"),
    @XmlEnumValue("Ardealite")
    ARDEALITE("Ardealite"),
    @XmlEnumValue("Ardennite")
    ARDENNITE("Ardennite"),
    @XmlEnumValue("Arfvedsonite")
    ARFVEDSONITE("Arfvedsonite"),
    @XmlEnumValue("Argentojarosite")
    ARGENTOJAROSITE("Argentojarosite"),
    @XmlEnumValue("Argentopentlandite")
    ARGENTOPENTLANDITE("Argentopentlandite"),
    @XmlEnumValue("Argentopyrite")
    ARGENTOPYRITE("Argentopyrite"),
    @XmlEnumValue("Argentotennantite")
    ARGENTOTENNANTITE("Argentotennantite"),
    @XmlEnumValue("Argutite")
    ARGUTITE("Argutite"),
    @XmlEnumValue("Argyrodite")
    ARGYRODITE("Argyrodite"),
    @XmlEnumValue("Arhbarite")
    ARHBARITE("Arhbarite"),
    @XmlEnumValue("Aristarainite")
    ARISTARAINITE("Aristarainite"),
    @XmlEnumValue("Armalcolite")
    ARMALCOLITE("Armalcolite"),
    @XmlEnumValue("Armangite")
    ARMANGITE("Armangite"),
    @XmlEnumValue("Armenite")
    ARMENITE("Armenite"),
    @XmlEnumValue("Armstrongite")
    ARMSTRONGITE("Armstrongite"),
    @XmlEnumValue("Arnhemite")
    ARNHEMITE("Arnhemite"),
    @XmlEnumValue("Arrojadite")
    ARROJADITE("Arrojadite"),
    @XmlEnumValue("Arsenbrackebuschite")
    ARSENBRACKEBUSCHITE("Arsenbrackebuschite"),
    @XmlEnumValue("Arsendescloizite")
    ARSENDESCLOIZITE("Arsendescloizite"),
    @XmlEnumValue("Arsenic")
    ARSENIC("Arsenic"),
    @XmlEnumValue("Arseniopleite")
    ARSENIOPLEITE("Arseniopleite"),
    @XmlEnumValue("Arseniosiderite")
    ARSENIOSIDERITE("Arseniosiderite"),
    @XmlEnumValue("Arsenobismite")
    ARSENOBISMITE("Arsenobismite"),
    @XmlEnumValue("Arsenoclasite")
    ARSENOCLASITE("Arsenoclasite"),
    @XmlEnumValue("Arsenocrandallite")
    ARSENOCRANDALLITE("Arsenocrandallite"),
    @XmlEnumValue("Arsenoflorencite-(Ce)")
    ARSENOFLORENCITE_CE("Arsenoflorencite-(Ce)"),
    @XmlEnumValue("Arsenogorceixite")
    ARSENOGORCEIXITE("Arsenogorceixite"),
    @XmlEnumValue("Arsenogoyazite")
    ARSENOGOYAZITE("Arsenogoyazite"),
    @XmlEnumValue("Arsenohauchecornite")
    ARSENOHAUCHECORNITE("Arsenohauchecornite"),
    @XmlEnumValue("Arsenolamprite")
    ARSENOLAMPRITE("Arsenolamprite"),
    @XmlEnumValue("Arsenolite")
    ARSENOLITE("Arsenolite"),
    @XmlEnumValue("Arsenopalladinite")
    ARSENOPALLADINITE("Arsenopalladinite"),
    @XmlEnumValue("Arsenopyrite")
    ARSENOPYRITE("Arsenopyrite"),
    @XmlEnumValue("Arsenosulvanite")
    ARSENOSULVANITE("Arsenosulvanite"),
    @XmlEnumValue("Arsenpolybasite")
    ARSENPOLYBASITE("Arsenpolybasite"),
    @XmlEnumValue("Arsentsumebite")
    ARSENTSUMEBITE("Arsentsumebite"),
    @XmlEnumValue("Arsenuranospathite")
    ARSENURANOSPATHITE("Arsenuranospathite"),
    @XmlEnumValue("Arsenuranylite")
    ARSENURANYLITE("Arsenuranylite"),
    @XmlEnumValue("Arthurite")
    ARTHURITE("Arthurite"),
    @XmlEnumValue("Artinite")
    ARTINITE("Artinite"),
    @XmlEnumValue("Artroeite")
    ARTROEITE("Artroeite"),
    @XmlEnumValue("Arupite")
    ARUPITE("Arupite"),
    @XmlEnumValue("Arzakite")
    ARZAKITE("Arzakite"),
    @XmlEnumValue("Asbecasite")
    ASBECASITE("Asbecasite"),
    @XmlEnumValue("Asbestos")
    ASBESTOS("Asbestos"),
    @XmlEnumValue("Asbolane")
    ASBOLANE("Asbolane"),
    @XmlEnumValue("Aschamalmite")
    ASCHAMALMITE("Aschamalmite"),
    @XmlEnumValue("Ashanite")
    ASHANITE("Ashanite"),
    @XmlEnumValue("Ashburtonite")
    ASHBURTONITE("Ashburtonite"),
    @XmlEnumValue("Ashcroftine-(Y)")
    ASHCROFTINE_Y("Ashcroftine-(Y)"),
    @XmlEnumValue("Ashoverite")
    ASHOVERITE("Ashoverite"),
    @XmlEnumValue("Asisite")
    ASISITE("Asisite"),
    @XmlEnumValue("Aspidolite")
    ASPIDOLITE("Aspidolite"),
    @XmlEnumValue("Asselbornite")
    ASSELBORNITE("Asselbornite"),
    @XmlEnumValue("Astrocyanite-(Ce)")
    ASTROCYANITE_CE("Astrocyanite-(Ce)"),
    @XmlEnumValue("Astrophyllite")
    ASTROPHYLLITE("Astrophyllite"),
    @XmlEnumValue("Atacamite")
    ATACAMITE("Atacamite"),
    @XmlEnumValue("Atelestite")
    ATELESTITE("Atelestite"),
    @XmlEnumValue("Athabascaite")
    ATHABASCAITE("Athabascaite"),
    @XmlEnumValue("Atheneite")
    ATHENEITE("Atheneite"),
    @XmlEnumValue("Atlasovite")
    ATLASOVITE("Atlasovite"),
    @XmlEnumValue("Atokite")
    ATOKITE("Atokite"),
    @XmlEnumValue("Attakolite")
    ATTAKOLITE("Attakolite"),
    @XmlEnumValue("Aubertite")
    AUBERTITE("Aubertite"),
    @XmlEnumValue("Augelite")
    AUGELITE("Augelite"),
    @XmlEnumValue("Augite")
    AUGITE("Augite"),
    @XmlEnumValue("Aurantimonate")
    AURANTIMONATE("Aurantimonate"),
    @XmlEnumValue("Aurichalcite")
    AURICHALCITE("Aurichalcite"),
    @XmlEnumValue("Auricupride")
    AURICUPRIDE("Auricupride"),
    @XmlEnumValue("Aurorite")
    AURORITE("Aurorite"),
    @XmlEnumValue("Aurostibite")
    AUROSTIBITE("Aurostibite"),
    @XmlEnumValue("Austinite")
    AUSTINITE("Austinite"),
    @XmlEnumValue("Autunite")
    AUTUNITE("Autunite"),
    @XmlEnumValue("Averievite")
    AVERIEVITE("Averievite"),
    @XmlEnumValue("Avicennite")
    AVICENNITE("Avicennite"),
    @XmlEnumValue("Avogadrite")
    AVOGADRITE("Avogadrite"),
    @XmlEnumValue("Awaruite")
    AWARUITE("Awaruite"),
    @XmlEnumValue("Azoproite")
    AZOPROITE("Azoproite"),
    @XmlEnumValue("Azurite")
    AZURITE("Azurite"),
    @XmlEnumValue("Babefphite")
    BABEFPHITE("Babefphite"),
    @XmlEnumValue("Babingtonite")
    BABINGTONITE("Babingtonite"),
    @XmlEnumValue("Babkinite")
    BABKINITE("Babkinite"),
    @XmlEnumValue("Baddeleyite")
    BADDELEYITE("Baddeleyite"),
    @XmlEnumValue("Bafertisite")
    BAFERTISITE("Bafertisite"),
    @XmlEnumValue("Baghdadite")
    BAGHDADITE("Baghdadite"),
    @XmlEnumValue("Bahianite")
    BAHIANITE("Bahianite"),
    @XmlEnumValue("Baileychlore")
    BAILEYCHLORE("Baileychlore"),
    @XmlEnumValue("Baiyuneboite")
    BAIYUNEBOITE("Baiyuneboite"),
    @XmlEnumValue("Baiyuneboite-(Ce)")
    BAIYUNEBOITE_CE("Baiyuneboite-(Ce)"),
    @XmlEnumValue("Bakerite")
    BAKERITE("Bakerite"),
    @XmlEnumValue("Bakhchisaraitsevite")
    BAKHCHISARAITSEVITE("Bakhchisaraitsevite"),
    @XmlEnumValue("Baksanite")
    BAKSANITE("Baksanite"),
    @XmlEnumValue("Balangeroite")
    BALANGEROITE("Balangeroite"),
    @XmlEnumValue("Balavinskite")
    BALAVINSKITE("Balavinskite"),
    @XmlEnumValue("Balipholite")
    BALIPHOLITE("Balipholite"),
    @XmlEnumValue("Balkanite")
    BALKANITE("Balkanite"),
    @XmlEnumValue("Balyakinite")
    BALYAKINITE("Balyakinite"),
    @XmlEnumValue("Bambollaite")
    BAMBOLLAITE("Bambollaite"),
    @XmlEnumValue("Bamfordite")
    BAMFORDITE("Bamfordite"),
    @XmlEnumValue("Banalsite")
    BANALSITE("Banalsite"),
    @XmlEnumValue("Bandylite")
    BANDYLITE("Bandylite"),
    @XmlEnumValue("Bannermanite")
    BANNERMANITE("Bannermanite"),
    @XmlEnumValue("Bannisterite")
    BANNISTERITE("Bannisterite"),
    @XmlEnumValue("Baotite")
    BAOTITE("Baotite"),
    @XmlEnumValue("Bararite")
    BARARITE("Bararite"),
    @XmlEnumValue("Baratovite")
    BARATOVITE("Baratovite"),
    @XmlEnumValue("Barberiite")
    BARBERIITE("Barberiite"),
    @XmlEnumValue("Barbertonite")
    BARBERTONITE("Barbertonite"),
    @XmlEnumValue("Barbosalite")
    BARBOSALITE("Barbosalite"),
    @XmlEnumValue("Barentsite")
    BARENTSITE("Barentsite"),
    @XmlEnumValue("Bariandite")
    BARIANDITE("Bariandite"),
    @XmlEnumValue("Baricite")
    BARICITE("Baricite"),
    @XmlEnumValue("Bario-orthojoaquinite")
    BARIO_ORTHOJOAQUINITE("Bario-orthojoaquinite"),
    @XmlEnumValue("Bariomicrolite")
    BARIOMICROLITE("Bariomicrolite"),
    @XmlEnumValue("Bariopyrochlore")
    BARIOPYROCHLORE("Bariopyrochlore"),
    @XmlEnumValue("Bariosincosite")
    BARIOSINCOSITE("Bariosincosite"),
    @XmlEnumValue("Barite")
    BARITE("Barite"),
    @XmlEnumValue("Barium-pharmacosiderite")
    BARIUM_PHARMACOSIDERITE("Barium-pharmacosiderite"),
    @XmlEnumValue("Barnesite")
    BARNESITE("Barnesite"),
    @XmlEnumValue("Barquillite")
    BARQUILLITE("Barquillite"),
    @XmlEnumValue("Barrerite")
    BARRERITE("Barrerite"),
    @XmlEnumValue("Barringerite")
    BARRINGERITE("Barringerite"),
    @XmlEnumValue("Barringtonite")
    BARRINGTONITE("Barringtonite"),
    @XmlEnumValue("Barroisite")
    BARROISITE("Barroisite"),
    @XmlEnumValue("Barstowite")
    BARSTOWITE("Barstowite"),
    @XmlEnumValue("Bartelkeite")
    BARTELKEITE("Bartelkeite"),
    @XmlEnumValue("Bartonite")
    BARTONITE("Bartonite"),
    @XmlEnumValue("Barylite")
    BARYLITE("Barylite"),
    @XmlEnumValue("Barysilite")
    BARYSILITE("Barysilite"),
    @XmlEnumValue("Barytocalcite")
    BARYTOCALCITE("Barytocalcite"),
    @XmlEnumValue("Barytolamprophyllite")
    BARYTOLAMPROPHYLLITE("Barytolamprophyllite"),
    @XmlEnumValue("Basaluminite")
    BASALUMINITE("Basaluminite"),
    @XmlEnumValue("Bassanite")
    BASSANITE("Bassanite"),
    @XmlEnumValue("Bassetite")
    BASSETITE("Bassetite"),
    @XmlEnumValue("Bastnasite")
    BASTNASITE("Bastnasite"),
    @XmlEnumValue("Bastnasite-(Ce)")
    BASTNASITE_CE("Bastnasite-(Ce)"),
    @XmlEnumValue("Bastnasite-(La)")
    BASTNASITE_LA("Bastnasite-(La)"),
    @XmlEnumValue("Bastnasite-(Y)")
    BASTNASITE_Y("Bastnasite-(Y)"),
    @XmlEnumValue("Batiferrite")
    BATIFERRITE("Batiferrite"),
    @XmlEnumValue("Batisite")
    BATISITE("Batisite"),
    @XmlEnumValue("Baumhauerite")
    BAUMHAUERITE("Baumhauerite"),
    @XmlEnumValue("Baumhauerite-2a")
    BAUMHAUERITE_2_A("Baumhauerite-2a"),
    @XmlEnumValue("Baumite")
    BAUMITE("Baumite"),
    @XmlEnumValue("Baumstarkite")
    BAUMSTARKITE("Baumstarkite"),
    @XmlEnumValue("Bauranoite")
    BAURANOITE("Bauranoite"),
    @XmlEnumValue("Bauxite(GeneralTerm)")
    BAUXITE_GENERAL_TERM("Bauxite(GeneralTerm)"),
    @XmlEnumValue("Bavenite")
    BAVENITE("Bavenite"),
    @XmlEnumValue("Bayankhanite")
    BAYANKHANITE("Bayankhanite"),
    @XmlEnumValue("Bayerite")
    BAYERITE("Bayerite"),
    @XmlEnumValue("Bayldonite")
    BAYLDONITE("Bayldonite"),
    @XmlEnumValue("Bayleyite")
    BAYLEYITE("Bayleyite"),
    @XmlEnumValue("Baylissite")
    BAYLISSITE("Baylissite"),
    @XmlEnumValue("Bazhenovite")
    BAZHENOVITE("Bazhenovite"),
    @XmlEnumValue("Bazirite")
    BAZIRITE("Bazirite"),
    @XmlEnumValue("Bazzite")
    BAZZITE("Bazzite"),
    @XmlEnumValue("Bearsite")
    BEARSITE("Bearsite"),
    @XmlEnumValue("Bearthite")
    BEARTHITE("Bearthite"),
    @XmlEnumValue("Beaverite")
    BEAVERITE("Beaverite"),
    @XmlEnumValue("Bechererite")
    BECHERERITE("Bechererite"),
    @XmlEnumValue("Becquerelite")
    BECQUERELITE("Becquerelite"),
    @XmlEnumValue("Bederite")
    BEDERITE("Bederite"),
    @XmlEnumValue("Behierite")
    BEHIERITE("Behierite"),
    @XmlEnumValue("Behoite")
    BEHOITE("Behoite"),
    @XmlEnumValue("Beidellite")
    BEIDELLITE("Beidellite"),
    @XmlEnumValue("Belendorffite")
    BELENDORFFITE("Belendorffite"),
    @XmlEnumValue("Belkovite")
    BELKOVITE("Belkovite"),
    @XmlEnumValue("Bellbergite")
    BELLBERGITE("Bellbergite"),
    @XmlEnumValue("Bellidoite")
    BELLIDOITE("Bellidoite"),
    @XmlEnumValue("Bellingerite")
    BELLINGERITE("Bellingerite"),
    @XmlEnumValue("Belloite")
    BELLOITE("Belloite"),
    @XmlEnumValue("Belovite-(Ce)")
    BELOVITE_CE("Belovite-(Ce)"),
    @XmlEnumValue("Belovite-(La)")
    BELOVITE_LA("Belovite-(La)"),
    @XmlEnumValue("Belyankinite")
    BELYANKINITE("Belyankinite"),
    @XmlEnumValue("Bementite")
    BEMENTITE("Bementite"),
    @XmlEnumValue("Benauite")
    BENAUITE("Benauite"),
    @XmlEnumValue("Benavidesite")
    BENAVIDESITE("Benavidesite"),
    @XmlEnumValue("Benitoite")
    BENITOITE("Benitoite"),
    @XmlEnumValue("Benjaminite")
    BENJAMINITE("Benjaminite"),
    @XmlEnumValue("Benleonardite")
    BENLEONARDITE("Benleonardite"),
    @XmlEnumValue("Benstonite")
    BENSTONITE("Benstonite"),
    @XmlEnumValue("Bentorite")
    BENTORITE("Bentorite"),
    @XmlEnumValue("Benyacarite")
    BENYACARITE("Benyacarite"),
    @XmlEnumValue("Beraunite")
    BERAUNITE("Beraunite"),
    @XmlEnumValue("Berborite")
    BERBORITE("Berborite"),
    @XmlEnumValue("Berborite-1t")
    BERBORITE_1_T("Berborite-1t"),
    @XmlEnumValue("Berdesinskiite")
    BERDESINSKIITE("Berdesinskiite"),
    @XmlEnumValue("Berezanskite")
    BEREZANSKITE("Berezanskite"),
    @XmlEnumValue("Bergenite")
    BERGENITE("Bergenite"),
    @XmlEnumValue("Bergslagite")
    BERGSLAGITE("Bergslagite"),
    @XmlEnumValue("Berlinite")
    BERLINITE("Berlinite"),
    @XmlEnumValue("Bermanite")
    BERMANITE("Bermanite"),
    @XmlEnumValue("Bernalite")
    BERNALITE("Bernalite"),
    @XmlEnumValue("Bernardite")
    BERNARDITE("Bernardite"),
    @XmlEnumValue("Berndtite")
    BERNDTITE("Berndtite"),
    @XmlEnumValue("Berndtite-2t")
    BERNDTITE_2_T("Berndtite-2t"),
    @XmlEnumValue("Berndtite-4h")
    BERNDTITE_4_H("Berndtite-4h"),
    @XmlEnumValue("Berryite")
    BERRYITE("Berryite"),
    @XmlEnumValue("Berthierine")
    BERTHIERINE("Berthierine"),
    @XmlEnumValue("Berthierite")
    BERTHIERITE("Berthierite"),
    @XmlEnumValue("Bertossaite")
    BERTOSSAITE("Bertossaite"),
    @XmlEnumValue("Bertrandite")
    BERTRANDITE("Bertrandite"),
    @XmlEnumValue("Beryl")
    BERYL("Beryl"),
    @XmlEnumValue("Beryllite")
    BERYLLITE("Beryllite"),
    @XmlEnumValue("Beryllonite")
    BERYLLONITE("Beryllonite"),
    @XmlEnumValue("Berzelianite")
    BERZELIANITE("Berzelianite"),
    @XmlEnumValue("Berzeliite")
    BERZELIITE("Berzeliite"),
    @XmlEnumValue("Bessmertnovite")
    BESSMERTNOVITE("Bessmertnovite"),
    @XmlEnumValue("Beta-fergusonite-(Ce)")
    BETA_FERGUSONITE_CE("Beta-fergusonite-(Ce)"),
    @XmlEnumValue("Beta-fergusonite-(Nd)")
    BETA_FERGUSONITE_ND("Beta-fergusonite-(Nd)"),
    @XmlEnumValue("Beta-fergusonite-(Y)")
    BETA_FERGUSONITE_Y("Beta-fergusonite-(Y)"),
    @XmlEnumValue("Betafite")
    BETAFITE("Betafite"),
    @XmlEnumValue("Betekhtinite")
    BETEKHTINITE("Betekhtinite"),
    @XmlEnumValue("Betpakdalite")
    BETPAKDALITE("Betpakdalite"),
    @XmlEnumValue("Beudantite")
    BEUDANTITE("Beudantite"),
    @XmlEnumValue("Beusite")
    BEUSITE("Beusite"),
    @XmlEnumValue("Beyerite")
    BEYERITE("Beyerite"),
    @XmlEnumValue("Bezsmertnovite")
    BEZSMERTNOVITE("Bezsmertnovite"),
    @XmlEnumValue("Bianchite")
    BIANCHITE("Bianchite"),
    @XmlEnumValue("Bicchulite")
    BICCHULITE("Bicchulite"),
    @XmlEnumValue("Bideauxite")
    BIDEAUXITE("Bideauxite"),
    @XmlEnumValue("Bieberite")
    BIEBERITE("Bieberite"),
    @XmlEnumValue("Biehlite")
    BIEHLITE("Biehlite"),
    @XmlEnumValue("Bigcreekite")
    BIGCREEKITE("Bigcreekite"),
    @XmlEnumValue("Bijvoetite-(Y)")
    BIJVOETITE_Y("Bijvoetite-(Y)"),
    @XmlEnumValue("Bikitaite")
    BIKITAITE("Bikitaite"),
    @XmlEnumValue("Bilibinskite")
    BILIBINSKITE("Bilibinskite"),
    @XmlEnumValue("Bilinite")
    BILINITE("Bilinite"),
    @XmlEnumValue("Billietite")
    BILLIETITE("Billietite"),
    @XmlEnumValue("Billingsleyite")
    BILLINGSLEYITE("Billingsleyite"),
    @XmlEnumValue("Bindheimite")
    BINDHEIMITE("Bindheimite"),
    @XmlEnumValue("Biotite")
    BIOTITE("Biotite"),
    @XmlEnumValue("Biphosphammite")
    BIPHOSPHAMMITE("Biphosphammite"),
    @XmlEnumValue("Biringuccite")
    BIRINGUCCITE("Biringuccite"),
    @XmlEnumValue("Birnessite")
    BIRNESSITE("Birnessite"),
    @XmlEnumValue("Bischofite")
    BISCHOFITE("Bischofite"),
    @XmlEnumValue("Bismite")
    BISMITE("Bismite"),
    @XmlEnumValue("Bismoclite")
    BISMOCLITE("Bismoclite"),
    @XmlEnumValue("Bismuth")
    BISMUTH("Bismuth"),
    @XmlEnumValue("Bismuthinite")
    BISMUTHINITE("Bismuthinite"),
    @XmlEnumValue("Bismutite")
    BISMUTITE("Bismutite"),
    @XmlEnumValue("Bismutocolumbite")
    BISMUTOCOLUMBITE("Bismutocolumbite"),
    @XmlEnumValue("Bismutoferrite")
    BISMUTOFERRITE("Bismutoferrite"),
    @XmlEnumValue("Bismutohauchecornite")
    BISMUTOHAUCHECORNITE("Bismutohauchecornite"),
    @XmlEnumValue("Bismutomicrolite")
    BISMUTOMICROLITE("Bismutomicrolite"),
    @XmlEnumValue("Bismutopyrochlore")
    BISMUTOPYROCHLORE("Bismutopyrochlore"),
    @XmlEnumValue("Bismutostibiconite")
    BISMUTOSTIBICONITE("Bismutostibiconite"),
    @XmlEnumValue("Bismutotantalite")
    BISMUTOTANTALITE("Bismutotantalite"),
    @XmlEnumValue("Bityite")
    BITYITE("Bityite"),
    @XmlEnumValue("Bixbyite")
    BIXBYITE("Bixbyite"),
    @XmlEnumValue("Bjarebyite")
    BJAREBYITE("Bjarebyite"),
    @XmlEnumValue("Blakeite")
    BLAKEITE("Blakeite"),
    @XmlEnumValue("Blatonite")
    BLATONITE("Blatonite"),
    @XmlEnumValue("Blatterite")
    BLATTERITE("Blatterite"),
    @XmlEnumValue("Bleasdaleite")
    BLEASDALEITE("Bleasdaleite"),
    @XmlEnumValue("Blixite")
    BLIXITE("Blixite"),
    @XmlEnumValue("Blodite")
    BLODITE("Blodite"),
    @XmlEnumValue("Blossite")
    BLOSSITE("Blossite"),
    @XmlEnumValue("Bobfergusonite")
    BOBFERGUSONITE("Bobfergusonite"),
    @XmlEnumValue("Bobierrite")
    BOBIERRITE("Bobierrite"),
    @XmlEnumValue("Bogdanovite")
    BOGDANOVITE("Bogdanovite"),
    @XmlEnumValue("Boggildite")
    BOGGILDITE("Boggildite"),
    @XmlEnumValue("Boggsite")
    BOGGSITE("Boggsite"),
    @XmlEnumValue("Bogvadite")
    BOGVADITE("Bogvadite"),
    @XmlEnumValue("Bohdanowiczite")
    BOHDANOWICZITE("Bohdanowiczite"),
    @XmlEnumValue("Bohmite")
    BOHMITE("Bohmite"),
    @XmlEnumValue("Bokite")
    BOKITE("Bokite"),
    @XmlEnumValue("Boleite")
    BOLEITE("Boleite"),
    @XmlEnumValue("Bolivarite")
    BOLIVARITE("Bolivarite"),
    @XmlEnumValue("Boltwoodite")
    BOLTWOODITE("Boltwoodite"),
    @XmlEnumValue("Bonaccordite")
    BONACCORDITE("Bonaccordite"),
    @XmlEnumValue("Bonattite")
    BONATTITE("Bonattite"),
    @XmlEnumValue("Bonshtedtite")
    BONSHTEDTITE("Bonshtedtite"),
    @XmlEnumValue("Boothite")
    BOOTHITE("Boothite"),
    @XmlEnumValue("Boracite")
    BORACITE("Boracite"),
    @XmlEnumValue("Boralsilite")
    BORALSILITE("Boralsilite"),
    @XmlEnumValue("Borax")
    BORAX("Borax"),
    @XmlEnumValue("Borcarite")
    BORCARITE("Borcarite"),
    @XmlEnumValue("Borishanskiite")
    BORISHANSKIITE("Borishanskiite"),
    @XmlEnumValue("Bornemanite")
    BORNEMANITE("Bornemanite"),
    @XmlEnumValue("Bornhardtite")
    BORNHARDTITE("Bornhardtite"),
    @XmlEnumValue("Bornite")
    BORNITE("Bornite"),
    @XmlEnumValue("Borodaevite")
    BORODAEVITE("Borodaevite"),
    @XmlEnumValue("Boromuscovite")
    BOROMUSCOVITE("Boromuscovite"),
    @XmlEnumValue("Borovskite")
    BOROVSKITE("Borovskite"),
    @XmlEnumValue("Bostwickite")
    BOSTWICKITE("Bostwickite"),
    @XmlEnumValue("Botallackite")
    BOTALLACKITE("Botallackite"),
    @XmlEnumValue("Botryogen")
    BOTRYOGEN("Botryogen"),
    @XmlEnumValue("Bottinoite")
    BOTTINOITE("Bottinoite"),
    @XmlEnumValue("Boulangerite")
    BOULANGERITE("Boulangerite"),
    @XmlEnumValue("Bournonite")
    BOURNONITE("Bournonite"),
    @XmlEnumValue("Boussingaultite")
    BOUSSINGAULTITE("Boussingaultite"),
    @XmlEnumValue("Boussingualtite")
    BOUSSINGUALTITE("Boussingualtite"),
    @XmlEnumValue("Bowieite")
    BOWIEITE("Bowieite"),
    @XmlEnumValue("Boyleite")
    BOYLEITE("Boyleite"),
    @XmlEnumValue("Brabantite")
    BRABANTITE("Brabantite"),
    @XmlEnumValue("Bracewellite")
    BRACEWELLITE("Bracewellite"),
    @XmlEnumValue("Brackebuschite")
    BRACKEBUSCHITE("Brackebuschite"),
    @XmlEnumValue("Bradleyite")
    BRADLEYITE("Bradleyite"),
    @XmlEnumValue("Braggite")
    BRAGGITE("Braggite"),
    @XmlEnumValue("Braitschite-(Ce)")
    BRAITSCHITE_CE("Braitschite-(Ce)"),
    @XmlEnumValue("Brammallite")
    BRAMMALLITE("Brammallite"),
    @XmlEnumValue("Brandholzite")
    BRANDHOLZITE("Brandholzite"),
    @XmlEnumValue("Brandtite")
    BRANDTITE("Brandtite"),
    @XmlEnumValue("Brannerite")
    BRANNERITE("Brannerite"),
    @XmlEnumValue("Brannockite")
    BRANNOCKITE("Brannockite"),
    @XmlEnumValue("Brassite")
    BRASSITE("Brassite"),
    @XmlEnumValue("Braunite")
    BRAUNITE("Braunite"),
    @XmlEnumValue("Bravoite")
    BRAVOITE("Bravoite"),
    @XmlEnumValue("Brazilianite")
    BRAZILIANITE("Brazilianite"),
    @XmlEnumValue("Bredigite")
    BREDIGITE("Bredigite"),
    @XmlEnumValue("Breithauptite")
    BREITHAUPTITE("Breithauptite"),
    @XmlEnumValue("Brenkite")
    BRENKITE("Brenkite"),
    @XmlEnumValue("Brewsterite")
    BREWSTERITE("Brewsterite"),
    @XmlEnumValue("Brewsterite-Ba")
    BREWSTERITE_BA("Brewsterite-Ba"),
    @XmlEnumValue("Brewsterite-Sr")
    BREWSTERITE_SR("Brewsterite-Sr"),
    @XmlEnumValue("Brezinaite")
    BREZINAITE("Brezinaite"),
    @XmlEnumValue("Brianite")
    BRIANITE("Brianite"),
    @XmlEnumValue("Brianroulstonite")
    BRIANROULSTONITE("Brianroulstonite"),
    @XmlEnumValue("Brianyoungite")
    BRIANYOUNGITE("Brianyoungite"),
    @XmlEnumValue("Briartite")
    BRIARTITE("Briartite"),
    @XmlEnumValue("Brindleyite")
    BRINDLEYITE("Brindleyite"),
    @XmlEnumValue("Britholite")
    BRITHOLITE("Britholite"),
    @XmlEnumValue("Britholite-(Ce)")
    BRITHOLITE_CE("Britholite-(Ce)"),
    @XmlEnumValue("Britholite-(Y)")
    BRITHOLITE_Y("Britholite-(Y)"),
    @XmlEnumValue("Brizziite")
    BRIZZIITE("Brizziite"),
    @XmlEnumValue("Brochantite")
    BROCHANTITE("Brochantite"),
    @XmlEnumValue("Brockite")
    BROCKITE("Brockite"),
    @XmlEnumValue("Brokenhillite")
    BROKENHILLITE("Brokenhillite"),
    @XmlEnumValue("Bromargyrite")
    BROMARGYRITE("Bromargyrite"),
    @XmlEnumValue("Bromellite")
    BROMELLITE("Bromellite"),
    @XmlEnumValue("Brookite")
    BROOKITE("Brookite"),
    @XmlEnumValue("Brownmillerite")
    BROWNMILLERITE("Brownmillerite"),
    @XmlEnumValue("Brucite")
    BRUCITE("Brucite"),
    @XmlEnumValue("Bruggenite")
    BRUGGENITE("Bruggenite"),
    @XmlEnumValue("Brugnatellite")
    BRUGNATELLITE("Brugnatellite"),
    @XmlEnumValue("Brunogeierite")
    BRUNOGEIERITE("Brunogeierite"),
    @XmlEnumValue("Brushite")
    BRUSHITE("Brushite"),
    @XmlEnumValue("Buchwaldite")
    BUCHWALDITE("Buchwaldite"),
    @XmlEnumValue("Buckhornite")
    BUCKHORNITE("Buckhornite"),
    @XmlEnumValue("Buddingtonite")
    BUDDINGTONITE("Buddingtonite"),
    @XmlEnumValue("Buergerite")
    BUERGERITE("Buergerite"),
    @XmlEnumValue("Buetschliite")
    BUETSCHLIITE("Buetschliite"),
    @XmlEnumValue("Bukovite")
    BUKOVITE("Bukovite"),
    @XmlEnumValue("Bukovskyite")
    BUKOVSKYITE("Bukovskyite"),
    @XmlEnumValue("Bulachite")
    BULACHITE("Bulachite"),
    @XmlEnumValue("Bultfonteinite")
    BULTFONTEINITE("Bultfonteinite"),
    @XmlEnumValue("Bunsenite")
    BUNSENITE("Bunsenite"),
    @XmlEnumValue("Burangaite")
    BURANGAITE("Burangaite");
    private final String value;

    MineralDetails1(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MineralDetails1 fromValue(String v) {
        for (MineralDetails1 c: MineralDetails1.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
