/*
 * Copyright 2016 CIRDLES.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 * Any modifications to this file will be lost upon recompilation of the source schema. 
 * Generated on: 2016.03.03 at 09:06:25 AM EST 
*/


package org.geosamples.samples;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sample package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final String GEOSAMPLES_URL = "http://app.geosamples.org";
    private static final QName _Url_QNAME = new QName(GEOSAMPLES_URL, "url");
    private static final QName _CollectorDetail_QNAME = new QName(GEOSAMPLES_URL, "collector_detail");
    private static final QName _Country_QNAME = new QName(GEOSAMPLES_URL, "country");
    private static final QName _Size_QNAME = new QName(GEOSAMPLES_URL, "size");
    private static final QName _PrimaryLocationType_QNAME = new QName(GEOSAMPLES_URL, "primary_location_type");
    private static final QName _County_QNAME = new QName(GEOSAMPLES_URL, "county");
    private static final QName _CurrentArchive_QNAME = new QName(GEOSAMPLES_URL, "current_archive");
    private static final QName _UrlType_QNAME = new QName(GEOSAMPLES_URL, "url_type");
    private static final QName _PlatformType_QNAME = new QName(GEOSAMPLES_URL, "platform_type");
    private static final QName _CruiseFieldPrgrm_QNAME = new QName(GEOSAMPLES_URL, "cruise_field_prgrm");
    private static final QName _LaunchPlatformName_QNAME = new QName(GEOSAMPLES_URL, "launch_platform_name");
    private static final QName _SampleComment_QNAME = new QName(GEOSAMPLES_URL, "sample_comment");
    private static final QName _Northing_QNAME = new QName(GEOSAMPLES_URL, "northing");
    private static final QName _GeologicalAge_QNAME = new QName(GEOSAMPLES_URL, "geological_age");
    private static final QName _AgeUnit_QNAME = new QName(GEOSAMPLES_URL, "age_unit");
    private static final QName _IsPrivate_QNAME = new QName(GEOSAMPLES_URL, "is_private");
    private static final QName _Latitude_QNAME = new QName(GEOSAMPLES_URL, "latitude");
    private static final QName _OriginalArchiveContact_QNAME = new QName(GEOSAMPLES_URL, "original_archive_contact");
    private static final QName _SizeUnit_QNAME = new QName(GEOSAMPLES_URL, "size_unit");
    private static final QName _PlatformDescr_QNAME = new QName(GEOSAMPLES_URL, "platform_descr");
    private static final QName _FieldName_QNAME = new QName(GEOSAMPLES_URL, "field_name");
    private static final QName _DepthMin_QNAME = new QName(GEOSAMPLES_URL, "depth_min");
    private static final QName _CollectionMethod_QNAME = new QName(GEOSAMPLES_URL, "collection_method");
    private static final QName _City_QNAME = new QName(GEOSAMPLES_URL, "city");
    private static final QName _UserCode_QNAME = new QName(GEOSAMPLES_URL, "user_code");
    private static final QName _CollectionStartDate_QNAME = new QName(GEOSAMPLES_URL, "collection_start_date");
    private static final QName _DepthMax_QNAME = new QName(GEOSAMPLES_URL, "depth_max");
    private static final QName _LocationDescription_QNAME = new QName(GEOSAMPLES_URL, "location_description");
    private static final QName _PlatformName_QNAME = new QName(GEOSAMPLES_URL, "platform_name");
    private static final QName _Description_QNAME = new QName(GEOSAMPLES_URL, "description");
    private static final QName _UrlDescription_QNAME = new QName(GEOSAMPLES_URL, "url_description");
    private static final QName _Province_QNAME = new QName(GEOSAMPLES_URL, "province");
    private static final QName _LocalityDescription_QNAME = new QName(GEOSAMPLES_URL, "locality_description");
    private static final QName _OriginalArchive_QNAME = new QName(GEOSAMPLES_URL, "original_archive");
    private static final QName _Longitude_QNAME = new QName(GEOSAMPLES_URL, "longitude");
    private static final QName _PublishDate_QNAME = new QName(GEOSAMPLES_URL, "publish_date");
    private static final QName _Elevation_QNAME = new QName(GEOSAMPLES_URL, "elevation");
    private static final QName _CollectionDatePrecision_QNAME = new QName(GEOSAMPLES_URL, "collection_date_precision");
    private static final QName _Material_QNAME = new QName(GEOSAMPLES_URL, "material");
    private static final QName _AgeMax_QNAME = new QName(GEOSAMPLES_URL, "age_max");
    private static final QName _Easting_QNAME = new QName(GEOSAMPLES_URL, "easting");
    private static final QName _ParentIgsn_QNAME = new QName(GEOSAMPLES_URL, "parent_igsn");
    private static final QName _Igsn_QNAME = new QName(GEOSAMPLES_URL, "igsn");
    private static final QName _NavigationType_QNAME = new QName(GEOSAMPLES_URL, "navigation_type");
    private static final QName _CollectionEndDate_QNAME = new QName(GEOSAMPLES_URL, "collection_end_date");
    private static final QName _Zone_QNAME = new QName(GEOSAMPLES_URL, "zone");
    private static final QName _Locality_QNAME = new QName(GEOSAMPLES_URL, "locality");
    private static final QName _LaunchTypeName_QNAME = new QName(GEOSAMPLES_URL, "launch_type_name");
    private static final QName _SampleType_QNAME = new QName(GEOSAMPLES_URL, "sample_type");
    private static final QName _LongitudeEnd_QNAME = new QName(GEOSAMPLES_URL, "longitude_end");
    private static final QName _LatitudeEnd_QNAME = new QName(GEOSAMPLES_URL, "latitude_end");
    private static final QName _VerticalDatum_QNAME = new QName(GEOSAMPLES_URL, "vertical_datum");
    private static final QName _LaunchId_QNAME = new QName(GEOSAMPLES_URL, "launch_id");
    private static final QName _AgeMin_QNAME = new QName(GEOSAMPLES_URL, "age_min");
    private static final QName _ClassificationComment_QNAME = new QName(GEOSAMPLES_URL, "classification_comment");
    private static final QName _Purpose_QNAME = new QName(GEOSAMPLES_URL, "purpose");
    private static final QName _Name_QNAME = new QName(GEOSAMPLES_URL, "name");
    private static final QName _SampleOtherName_QNAME = new QName(GEOSAMPLES_URL, "sample_other_name");
    private static final QName _ElevationEnd_QNAME = new QName(GEOSAMPLES_URL, "elevation_end");
    private static final QName _Collector_QNAME = new QName(GEOSAMPLES_URL, "collector");
    private static final QName _GeologicalUnit_QNAME = new QName(GEOSAMPLES_URL, "geological_unit");
    private static final QName _PrimaryLocationName_QNAME = new QName(GEOSAMPLES_URL, "primary_location_name");
    private static final QName _DepthScale_QNAME = new QName(GEOSAMPLES_URL, "depth_scale");
    private static final QName _CurrentArchiveContact_QNAME = new QName(GEOSAMPLES_URL, "current_archive_contact");
    private static final QName _CollectionMethodDescr_QNAME = new QName(GEOSAMPLES_URL, "collection_method_descr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sample
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Samples }
     * 
     * @return Samples
     */
    public Samples createSamples() {
        return new Samples();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     * @return Classification
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link IgneousType }
     * 
     * @return IgneousType
     */
    public IgneousType createIgneousType() {
        return new IgneousType();
    }

    /**
     * Create an instance of {@link Classification.Rock }
     * 
     * @return Classification.Rock
     */
    public Classification.Rock createClassificationRock() {
        return new Classification.Rock();
    }

    /**
     * Create an instance of {@link Classification.Rock.Xenolithic }
     * 
     * @return Classification.Rock.Xenolithic
     */
    public Classification.Rock.Xenolithic createClassificationRockXenolithic() {
        return new Classification.Rock.Xenolithic();
    }

    /**
     * Create an instance of {@link Classification.Biology }
     * 
     * @return Classification.Biology
     */
    public Classification.Biology createClassificationBiology() {
        return new Classification.Biology();
    }

    /**
     * Create an instance of {@link Samples.Sample }
     * 
     * @return Samples.Sample
     */
    public Samples.Sample createSamplesSample() {
        return new Samples.Sample();
    }

    /**
     * Create an instance of {@link Samples.Sample.ExternalUrls }
     * 
     * @return Samples.Sample.ExternalUrls
     */
    public Samples.Sample.ExternalUrls createSamplesSampleExternalUrls() {
        return new Samples.Sample.ExternalUrls();
    }

    /**
     * Create an instance of {@link Classification.Mineral }
     * 
     * @return Classification.Mineral
     */
    public Classification.Mineral createClassificationMineral() {
        return new Classification.Mineral();
    }

    /**
     * Create an instance of {@link IgneousType.Plutonic }
     * 
     * @return IgneousType.Plutonic
     */
    public IgneousType.Plutonic createIgneousTypePlutonic() {
        return new IgneousType.Plutonic();
    }

    /**
     * Create an instance of {@link IgneousType.Volcanic }
     * 
     * @return 
     */
    public IgneousType.Volcanic createIgneousTypeVolcanic() {
        return new IgneousType.Volcanic();
    }

    /**
     * Create an instance of {@link Classification.Rock.Metamorphic }
     * 
     * @return 
     */
    public Classification.Rock.Metamorphic createClassificationRockMetamorphic() {
        return new Classification.Rock.Metamorphic();
    }

    /**
     * Create an instance of {@link Classification.Rock.Ore }
     * 
     * @return 
     */
    public Classification.Rock.Ore createClassificationRockOre() {
        return new Classification.Rock.Ore();
    }

    /**
     * Create an instance of {@link Classification.Rock.Sedimentary }
     * 
     * @return 
     */
    public Classification.Rock.Sedimentary createClassificationRockSedimentary() {
        return new Classification.Rock.Sedimentary();
    }

    /**
     * Create an instance of {@link Classification.Rock.Xenolithic.Metamorphic }
     * 
     * @return 
     */
    public Classification.Rock.Xenolithic.Metamorphic createClassificationRockXenolithicMetamorphic() {
        return new Classification.Rock.Xenolithic.Metamorphic();
    }

    /**
     * Create an instance of {@link Classification.Biology.Macrobiology }
     * 
     * @return 
     */
    public Classification.Biology.Macrobiology createClassificationBiologyMacrobiology() {
        return new Classification.Biology.Macrobiology();
    }

    /**
     * Create an instance of {@link Samples.Sample.SampleOtherNames }
     * 
     * @return 
     */
    public Samples.Sample.SampleOtherNames createSamplesSampleSampleOtherNames() {
        return new Samples.Sample.SampleOtherNames();
    }

    /**
     * Create an instance of {@link Samples.Sample.ExternalUrls.ExternalUrl }
     * 
     * @return 
     */
    public Samples.Sample.ExternalUrls.ExternalUrl createSamplesSampleExternalUrlsExternalUrl() {
        return new Samples.Sample.ExternalUrls.ExternalUrl();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "collector_detail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCollectorDetail(String value) {
        return new JAXBElement<>(_CollectorDetail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "country")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "size")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSize(String value) {
        return new JAXBElement<>(_Size_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "primary_location_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrimaryLocationType(String value) {
        return new JAXBElement<>(_PrimaryLocationType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "county")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCounty(String value) {
        return new JAXBElement<>(_County_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "current_archive")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCurrentArchive(String value) {
        return new JAXBElement<>(_CurrentArchive_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "url_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUrlType(String value) {
        return new JAXBElement<>(_UrlType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "platform_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPlatformType(String value) {
        return new JAXBElement<>(_PlatformType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "cruise_field_prgrm")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCruiseFieldPrgrm(String value) {
        return new JAXBElement<>(_CruiseFieldPrgrm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "launch_platform_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLaunchPlatformName(String value) {
        return new JAXBElement<>(_LaunchPlatformName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "sample_comment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSampleComment(String value) {
        return new JAXBElement<>(_SampleComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "northing")
    public JAXBElement<BigDecimal> createNorthing(BigDecimal value) {
        return new JAXBElement<>(_Northing_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "geological_age")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGeologicalAge(String value) {
        return new JAXBElement<>(_GeologicalAge_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "age_unit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAgeUnit(String value) {
        return new JAXBElement<>(_AgeUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "is_private", defaultValue = "0")
    public JAXBElement<BigInteger> createIsPrivate(BigInteger value) {
        return new JAXBElement<>(_IsPrivate_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "latitude")
    public JAXBElement<BigDecimal> createLatitude(BigDecimal value) {
        return new JAXBElement<>(_Latitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "original_archive_contact")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOriginalArchiveContact(String value) {
        return new JAXBElement<>(_OriginalArchiveContact_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "size_unit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSizeUnit(String value) {
        return new JAXBElement<>(_SizeUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "platform_descr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPlatformDescr(String value) {
        return new JAXBElement<>(_PlatformDescr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "field_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFieldName(String value) {
        return new JAXBElement<>(_FieldName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "depth_min")
    public JAXBElement<BigDecimal> createDepthMin(BigDecimal value) {
        return new JAXBElement<>(_DepthMin_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "collection_method")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCollectionMethod(String value) {
        return new JAXBElement<>(_CollectionMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "city")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "user_code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUserCode(String value) {
        return new JAXBElement<>(_UserCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "collection_start_date")
    public JAXBElement<XMLGregorianCalendar> createCollectionStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<>(_CollectionStartDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "depth_max")
    public JAXBElement<BigDecimal> createDepthMax(BigDecimal value) {
        return new JAXBElement<>(_DepthMax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "location_description")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLocationDescription(String value) {
        return new JAXBElement<>(_LocationDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "platform_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPlatformName(String value) {
        return new JAXBElement<>(_PlatformName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "description")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "url_description")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUrlDescription(String value) {
        return new JAXBElement<>(_UrlDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "province")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProvince(String value) {
        return new JAXBElement<>(_Province_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "locality_description")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLocalityDescription(String value) {
        return new JAXBElement<>(_LocalityDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "original_archive")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOriginalArchive(String value) {
        return new JAXBElement<>(_OriginalArchive_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "longitude")
    public JAXBElement<BigDecimal> createLongitude(BigDecimal value) {
        return new JAXBElement<>(_Longitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "publish_date")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPublishDate(String value) {
        return new JAXBElement<>(_PublishDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "elevation")
    public JAXBElement<BigDecimal> createElevation(BigDecimal value) {
        return new JAXBElement<>(_Elevation_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "collection_date_precision")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCollectionDatePrecision(String value) {
        return new JAXBElement<>(_CollectionDatePrecision_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "material")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMaterial(String value) {
        return new JAXBElement<>(_Material_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "age_max")
    public JAXBElement<BigDecimal> createAgeMax(BigDecimal value) {
        return new JAXBElement<>(_AgeMax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "easting")
    public JAXBElement<BigDecimal> createEasting(BigDecimal value) {
        return new JAXBElement<>(_Easting_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "parent_igsn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParentIgsn(String value) {
        return new JAXBElement<>(_ParentIgsn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "igsn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIgsn(String value) {
        return new JAXBElement<>(_Igsn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "navigation_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNavigationType(String value) {
        return new JAXBElement<>(_NavigationType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "collection_end_date")
    public JAXBElement<XMLGregorianCalendar> createCollectionEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<>(_CollectionEndDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "zone")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createZone(String value) {
        return new JAXBElement<>(_Zone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "locality")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLocality(String value) {
        return new JAXBElement<>(_Locality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "launch_type_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLaunchTypeName(String value) {
        return new JAXBElement<>(_LaunchTypeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "sample_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSampleType(String value) {
        return new JAXBElement<>(_SampleType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "longitude_end")
    public JAXBElement<BigDecimal> createLongitudeEnd(BigDecimal value) {
        return new JAXBElement<>(_LongitudeEnd_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "latitude_end")
    public JAXBElement<BigDecimal> createLatitudeEnd(BigDecimal value) {
        return new JAXBElement<>(_LatitudeEnd_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "vertical_datum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVerticalDatum(String value) {
        return new JAXBElement<>(_VerticalDatum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "launch_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLaunchId(String value) {
        return new JAXBElement<>(_LaunchId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "age_min")
    public JAXBElement<BigDecimal> createAgeMin(BigDecimal value) {
        return new JAXBElement<>(_AgeMin_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "classification_comment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createClassificationComment(String value) {
        return new JAXBElement<>(_ClassificationComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "purpose")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPurpose(String value) {
        return new JAXBElement<>(_Purpose_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "sample_other_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSampleOtherName(String value) {
        return new JAXBElement<>(_SampleOtherName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "elevation_end")
    public JAXBElement<BigDecimal> createElevationEnd(BigDecimal value) {
        return new JAXBElement<>(_ElevationEnd_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "collector")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCollector(String value) {
        return new JAXBElement<>(_Collector_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "geological_unit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGeologicalUnit(String value) {
        return new JAXBElement<>(_GeologicalUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "primary_location_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrimaryLocationName(String value) {
        return new JAXBElement<>(_PrimaryLocationName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "depth_scale")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDepthScale(String value) {
        return new JAXBElement<>(_DepthScale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "current_archive_contact")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCurrentArchiveContact(String value) {
        return new JAXBElement<>(_CurrentArchiveContact_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     * @param value
     * @return 
     */
    @XmlElementDecl(namespace = GEOSAMPLES_URL, name = "collection_method_descr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCollectionMethodDescr(String value) {
        return new JAXBElement<>(_CollectionMethodDescr_QNAME, String.class, null, value);
    }

}
