//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 08:40:30 AM EDT 
//


package org.geosamples.samples;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sample_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sample_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Bead"/&gt;
 *     &lt;enumeration value="Chemical Fraction"/&gt;
 *     &lt;enumeration value="Core"/&gt;
 *     &lt;enumeration value="Core Half Round"/&gt;
 *     &lt;enumeration value="Core Piece"/&gt;
 *     &lt;enumeration value="Core Quarter Round"/&gt;
 *     &lt;enumeration value="Core Section"/&gt;
 *     &lt;enumeration value="Core Section Half"/&gt;
 *     &lt;enumeration value="Core Sub-Piece"/&gt;
 *     &lt;enumeration value="Core Whole Round"/&gt;
 *     &lt;enumeration value="CTD"/&gt;
 *     &lt;enumeration value="Cube"/&gt;
 *     &lt;enumeration value="Culture"/&gt;
 *     &lt;enumeration value="Cuttings"/&gt;
 *     &lt;enumeration value="Cylinder"/&gt;
 *     &lt;enumeration value="Dredge"/&gt;
 *     &lt;enumeration value="Gas"/&gt;
 *     &lt;enumeration value="Grab"/&gt;
 *     &lt;enumeration value="Hole"/&gt;
 *     &lt;enumeration value="Individual Sample"/&gt;
 *     &lt;enumeration value="Liquid"/&gt;
 *     &lt;enumeration value="Mechanical Fraction"/&gt;
 *     &lt;enumeration value="Oriented Core"/&gt;
 *     &lt;enumeration value="Powder"/&gt;
 *     &lt;enumeration value="Rock Powder"/&gt;
 *     &lt;enumeration value="Site"/&gt;
 *     &lt;enumeration value="Slab"/&gt;
 *     &lt;enumeration value="Smear"/&gt;
 *     &lt;enumeration value="Specimen"/&gt;
 *     &lt;enumeration value="Squeeze Cake"/&gt;
 *     &lt;enumeration value="Terrestrial Section"/&gt;
 *     &lt;enumeration value="Thin Section"/&gt;
 *     &lt;enumeration value="Toothpick"/&gt;
 *     &lt;enumeration value="Trawl"/&gt;
 *     &lt;enumeration value="U-Channel"/&gt;
 *     &lt;enumeration value="Wedge"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "sample_type", namespace = "http://app.geosamples.org")
@XmlEnum
public enum SampleType {

    @XmlEnumValue("Bead")
    BEAD("Bead"),
    @XmlEnumValue("Chemical Fraction")
    CHEMICAL_FRACTION("Chemical Fraction"),
    @XmlEnumValue("Core")
    CORE("Core"),
    @XmlEnumValue("Core Half Round")
    CORE_HALF_ROUND("Core Half Round"),
    @XmlEnumValue("Core Piece")
    CORE_PIECE("Core Piece"),
    @XmlEnumValue("Core Quarter Round")
    CORE_QUARTER_ROUND("Core Quarter Round"),
    @XmlEnumValue("Core Section")
    CORE_SECTION("Core Section"),
    @XmlEnumValue("Core Section Half")
    CORE_SECTION_HALF("Core Section Half"),
    @XmlEnumValue("Core Sub-Piece")
    CORE_SUB_PIECE("Core Sub-Piece"),
    @XmlEnumValue("Core Whole Round")
    CORE_WHOLE_ROUND("Core Whole Round"),
    CTD("CTD"),
    @XmlEnumValue("Cube")
    CUBE("Cube"),
    @XmlEnumValue("Culture")
    CULTURE("Culture"),
    @XmlEnumValue("Cuttings")
    CUTTINGS("Cuttings"),
    @XmlEnumValue("Cylinder")
    CYLINDER("Cylinder"),
    @XmlEnumValue("Dredge")
    DREDGE("Dredge"),
    @XmlEnumValue("Gas")
    GAS("Gas"),
    @XmlEnumValue("Grab")
    GRAB("Grab"),
    @XmlEnumValue("Hole")
    HOLE("Hole"),
    @XmlEnumValue("Individual Sample")
    INDIVIDUAL_SAMPLE("Individual Sample"),
    @XmlEnumValue("Liquid")
    LIQUID("Liquid"),
    @XmlEnumValue("Mechanical Fraction")
    MECHANICAL_FRACTION("Mechanical Fraction"),
    @XmlEnumValue("Oriented Core")
    ORIENTED_CORE("Oriented Core"),
    @XmlEnumValue("Powder")
    POWDER("Powder"),
    @XmlEnumValue("Rock Powder")
    ROCK_POWDER("Rock Powder"),
    @XmlEnumValue("Site")
    SITE("Site"),
    @XmlEnumValue("Slab")
    SLAB("Slab"),
    @XmlEnumValue("Smear")
    SMEAR("Smear"),
    @XmlEnumValue("Specimen")
    SPECIMEN("Specimen"),
    @XmlEnumValue("Squeeze Cake")
    SQUEEZE_CAKE("Squeeze Cake"),
    @XmlEnumValue("Terrestrial Section")
    TERRESTRIAL_SECTION("Terrestrial Section"),
    @XmlEnumValue("Thin Section")
    THIN_SECTION("Thin Section"),
    @XmlEnumValue("Toothpick")
    TOOTHPICK("Toothpick"),
    @XmlEnumValue("Trawl")
    TRAWL("Trawl"),
    @XmlEnumValue("U-Channel")
    U_CHANNEL("U-Channel"),
    @XmlEnumValue("Wedge")
    WEDGE("Wedge"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    SampleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SampleType fromValue(String v) {
        for (SampleType c: SampleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
